import type { TripTemplateInput } from '@/shared/lib/trip-template'

/**
 * An illustrative itinerary used by the model-example action.
 * Times are planning placeholders, not promises about a carrier, timetable,
 * price, or opening hour. The content stays compact for viewer and print use.
 */
export const MODEL_EXAMPLE_TRIP_TEMPLATE = {
    title: '타이베이 모델 일정',
    eyebrow: 'TAIPEI / ILLUSTRATIVE 5 DAYS',
    destination: '타이베이',
    departureAirportCode: 'ICN',
    startDate: '2026-11-05',
    endDate: '2026-11-09',
    customNights: 4,
    customDays: 5,
    periodNote: '도시 3일 + 근교 1일',
    disclaimer: '항공·숙소는 예시 데이터이며 모든 시각·환승·운영 정보는 계획값입니다. 예약 전 공식 페이지에서 최신 정보를 확인하세요.',
    verifiedOn: null,
    bufferPolicy: '공항과 도시 간 이동에는 최소 30분, 예약 일정 앞뒤에는 20분의 여유를 둡니다. 교통 지연이 생기면 저녁의 여유 일정부터 줄입니다.',
    bookingNote:
        '먼저 항공·숙소와 우선순위 1~2 항목을 확인하고, 나머지는 공식 안내의 운영 조건을 본 뒤 확정합니다. 이 일정의 링크와 시각은 출발 전 다시 확인하세요.',
    footerNote:
        '모델 일정은 구조와 작성 방법을 보여 주기 위한 예시입니다. 실제 예약·운항·휴관·입장 조건은 각 기관의 공식 안내가 우선이며, 이 트립은 최신성을 보장하지 않습니다.',
    sidebarNote:
        '이 예시는 일정 종류, 이동시간, 체크리스트, 정보 섹션을 한 번에 살펴볼 수 있도록 구성했습니다. 마음에 드는 부분만 남기고 실제 여행에 맞게 바꿔 보세요.',
    destinations: [
        { countryCode: 'TW', city: '타이베이' },
        { countryCode: 'TW', city: '지우펀' },
    ],
    flights: [
        {
            direction: 'outbound',
            label: '11.05 목 · 출국 예시',
            departCode: 'ICN',
            departTime: '09:20',
            departTerminal: 'T1',
            arriveCode: 'TPE',
            arriveTime: '11:10',
            arriveTerminal: 'T1',
            flightNumber: null,
            note: '예시 구간. 항공사·편명·터미널은 예약 시 확인',
        },
        {
            direction: 'inbound',
            label: '11.09 월 · 귀국 예시',
            departCode: 'TPE',
            departTime: '18:30',
            departTerminal: 'T1',
            arriveCode: 'ICN',
            arriveTime: '22:00',
            arriveTerminal: 'T1',
            flightNumber: null,
            note: '예시 구간. 공항 도착 목표는 실제 항공사 안내에 맞춰 조정',
        },
    ],
    lodgings: [
        {
            name: '중산역 인근 예시 숙소',
            nameLocal: 'Illustrative stay near Zhongshan Station',
            address: 'Taipei City, Zhongshan District (example area)',
            accessNote: '타이베이역과 중산역 사이를 거점으로 삼는 예시 위치',
            checkIn: '15:00',
            checkOut: '11:00',
            url: 'https://www.google.com/maps/search/?api=1&query=Zhongshan+Station+Taipei+hotel',
            note: '실제 숙소를 정한 뒤 주소·체크인·짐 보관 조건을 교체',
        },
    ],
    sidebarLinks: [
        { label: '타이베이 공식 여행 안내', url: 'https://www.travel.taipei/en', description: '도시 명소·교통·여행 기본 정보' },
        { label: '타오위안공항 공식 안내', url: 'https://www.taoyuan-airport.com/english', description: '터미널과 공항 이동 정보 확인' },
        { label: '대만 관광청 공식 안내', url: 'https://eng.taiwan.net.tw/', description: '지역 관광과 여행 준비 정보' },
    ],
    scheduleKinds: [
        { key: 'planned', label: '계획', legendLabel: '계획 일정', colorToken: 'muted', bufferLabel: '마지막 10분 여유' },
        { key: 'confirmed', label: '확정 시각', legendLabel: '항공편·확정 약속', colorToken: 'success', bufferLabel: '전후 여유 10분' },
        { key: 'target', label: '예매 목표', legendLabel: '예매 목표·미확정', colorToken: 'warning', bufferLabel: '마지막 10분 여유' },
        { key: 'flexible', label: '여유', legendLabel: '식사·휴식·대안 일정', colorToken: 'chart-2', bufferLabel: '다음 일정 전 20분 여유' },
    ],
    days: [
        {
            date: '2026-11-05',
            shortLabel: '도착',
            title: '타이베이 도착과 강변 산책',
            subtitle: '11/5 목 · ICN 09:20 · TPE 11:10 예시',
            overview: '공항 수속과 시내 이동을 넉넉히 잡고, 숙소에 짐을 둔 뒤 다다오청 강변에서 첫 저녁을 보냅니다.',
            planHeadline: '도착일은 이동 후 한 곳만 방문합니다.',
            planNote: '입국 수속이 길어지면 강변 산책을 줄이고 식사와 숙소 휴식을 우선합니다.',
            closingHeadline: '첫날의 목표는 체크인과 다음 날 준비입니다.',
            closingNote: '교통카드·eSIM·우산처럼 다음 일정에 필요한 것을 저녁에 확인해 두면 아침이 여유롭습니다.',
            morningSummary: '항공 이동',
            afternoonSummary: '공항 → 숙소·체크인',
            eveningSummary: '다다오청 산책·저녁',
            facts: [
                { label: '출발 공항', value: '서울/인천(ICN), 제1터미널' },
                { label: '도착 공항', value: '타오위안(TPE), 제1터미널' },
                { label: '도시 이동', value: '공항 MRT 또는 공항 공식 교통 안내 확인' },
            ],
            routes: [
                {
                    origin: '타오위안공항',
                    destination: '중산역 인근 숙소',
                    minutes: 90,
                    pathText: '공항 수속 → 공항 MRT·도시역 → 숙소',
                    formula: '입국·수하물 50분 + 승차·환승·숙소 접근 40분의 계획값',
                },
                {
                    origin: '숙소',
                    destination: '다다오청 부두',
                    minutes: 30,
                    pathText: '중산역권 → 디화제 → 강변 산책',
                    formula: '도보와 신호 대기를 포함한 여유 있는 계획값',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '09:20~11:10',
                    title: '인천공항 → 타오위안공항',
                    kind: 'confirmed',
                    note: '예시 항공 구간. 실제 운항·편명·터미널은 예약 시 확인',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '11:10~12:20',
                    title: '입국심사·수하물·세관',
                    kind: 'planned',
                    note: '도착 수속을 위한 계획상 70분',
                    bufferNote: '대기시간 변동',
                    mapQuery: 'Taoyuan International Airport Terminal 1',
                },
                {
                    timeLabel: '12:20~13:50',
                    title: '공항에서 시내로 이동',
                    kind: 'planned',
                    note: '공항 MRT 또는 공식 교통 안내에 맞는 경로 선택',
                    bufferNote: '환승 20분 포함',
                    mapQuery: 'Taoyuan Airport MRT Taipei Main Station',
                },
                {
                    timeLabel: '13:50~14:30',
                    title: '숙소에 짐 보관·점심',
                    kind: 'planned',
                    note: '체크인 전이라면 프런트의 짐 보관 조건 확인',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
                {
                    timeLabel: '14:30~15:30',
                    title: '체크인 또는 카페 휴식',
                    kind: 'flexible',
                    note: '객실 준비 전에는 근처에서 쉬는 대안 일정',
                    bufferNote: '도착일 회복 시간',
                    mapQuery: null,
                },
                {
                    timeLabel: '16:00~17:30',
                    title: '디화제·다다오청 강변 산책',
                    kind: 'planned',
                    note: '첫날은 한 구역만 천천히 걷기',
                    bufferNote: '복귀 여유 20분',
                    mapQuery: 'Dadaocheng Wharf Taipei',
                },
                {
                    timeLabel: '17:30~19:00',
                    title: '다다오청 저녁',
                    kind: 'flexible',
                    note: '식당은 현장 상황에 맞춰 선택',
                    bufferNote: null,
                    mapQuery: 'Dihua Street Taipei',
                },
                {
                    timeLabel: '19:00 이후',
                    title: '숙소 복귀·다음 날 준비',
                    kind: 'planned',
                    note: '교통카드와 우천 대안을 확인',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
            ],
            notes: [
                {
                    leading: '공항 교통은 도착 터미널과 실제 운행 상황을 기준으로 선택합니다. ',
                    linkLabel: '타오위안공항 공식 교통 안내',
                    linkUrl: 'https://www.taoyuan-airport.com/english',
                    trailing: '에서 최신 안내를 확인하세요.',
                },
            ],
        },
        {
            date: '2026-11-06',
            shortLabel: '시내',
            title: '박물관과 중정기념당',
            subtitle: '11/6 금 · 한 구역씩 보는 도시 일정',
            overview: '오전에는 박물관, 오후에는 중정기념당과 융캉제를 묶어 실내·야외 리듬을 균형 있게 배치합니다.',
            planHeadline: '오전 예약 목표 하나와 오후 산책 하나만 둡니다.',
            planNote: '박물관 체류 시간이 늘어나면 융캉제의 식사·산책 순서를 줄여도 전체 흐름이 유지됩니다.',
            closingHeadline: '저녁은 숙소 근처에서 마무리합니다.',
            closingNote: '다음 날 온천 일정에 필요한 여벌 옷과 작은 수건을 전날 준비합니다.',
            morningSummary: '국립고궁박물관',
            afternoonSummary: '중정기념당·융캉제',
            eveningSummary: '저녁·휴식',
            facts: [],
            routes: [
                {
                    origin: '숙소',
                    destination: '국립고궁박물관',
                    minutes: 45,
                    pathText: '중산역권 → 시내 대중교통 → 박물관',
                    formula: '승차·환승 25분 + 입구 접근·대기 20분의 계획값',
                },
                {
                    origin: '국립고궁박물관',
                    destination: '중정기념당',
                    minutes: 55,
                    pathText: '박물관 → 시내 환승 → 중정기념당',
                    formula: '도시 이동 35분 + 점심 선택·환승 여유 20분',
                },
                { origin: '융캉제', destination: '숙소', minutes: 30, pathText: '융캉제 → 중산역권', formula: '도보·대중교통을 포함한 복귀 계획값' },
            ],
            scheduleItems: [
                {
                    timeLabel: '08:00~08:45',
                    title: '아침 식사·출발 준비',
                    kind: 'flexible',
                    note: '물과 간단한 간식을 챙기기',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
                {
                    timeLabel: '08:45~09:30',
                    title: '숙소 → 국립고궁박물관',
                    kind: 'planned',
                    note: '입장 목표보다 20분 먼저 도착하도록 계획',
                    bufferNote: '환승 여유 15분',
                    mapQuery: 'National Palace Museum Taipei',
                },
                {
                    timeLabel: '09:30~12:00',
                    title: '국립고궁박물관',
                    kind: 'target',
                    note: '전시·입장 조건은 공식 안내에서 출발 전 확인',
                    bufferNote: '관람 종료 여유 20분',
                    mapQuery: 'National Palace Museum Taipei',
                },
                {
                    timeLabel: '12:00~13:00',
                    title: '박물관 또는 시내 점심',
                    kind: 'flexible',
                    note: '대기열이 길면 다음 이동을 먼저 준비',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '13:00~14:00',
                    title: '중정기념당으로 이동',
                    kind: 'planned',
                    note: '이동 중 음료를 보충',
                    bufferNote: '도시 환승 여유 20분',
                    mapQuery: 'Chiang Kai-shek Memorial Hall Taipei',
                },
                {
                    timeLabel: '14:00~15:30',
                    title: '중정기념당·광장 산책',
                    kind: 'planned',
                    note: '실내 전시와 광장 중 컨디션에 맞춰 선택',
                    bufferNote: '다음 구역 이동 전 20분',
                    mapQuery: 'Chiang Kai-shek Memorial Hall Taipei',
                },
                {
                    timeLabel: '15:30~17:30',
                    title: '융캉제 산책·간식',
                    kind: 'planned',
                    note: '상점 방문은 두세 곳으로 제한',
                    bufferNote: '숙소 복귀 여유',
                    mapQuery: 'Yongkang Street Taipei',
                },
                {
                    timeLabel: '17:30~19:00',
                    title: '저녁 식사',
                    kind: 'flexible',
                    note: '예약이 필요한 식당은 별도 체크리스트에 추가',
                    bufferNote: null,
                    mapQuery: 'Yongkang Street Taipei',
                },
                {
                    timeLabel: '19:00 이후',
                    title: '숙소 복귀·온천 준비',
                    kind: 'planned',
                    note: '다음 날 실내·야외 대안을 함께 확인',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
            ],
            notes: [
                {
                    leading: '박물관 운영과 전시는 바뀔 수 있으므로 ',
                    linkLabel: '국립고궁박물관 공식 사이트',
                    linkUrl: 'https://www.npm.gov.tw/?l=2',
                    trailing: '를 출발 전 다시 확인합니다.',
                },
            ],
        },
        {
            date: '2026-11-07',
            shortLabel: '온천',
            title: '베이터우와 서문정',
            subtitle: '11/7 토 · 실내·야외 대안을 함께 둔 날',
            overview: '오전에는 베이터우의 온천 문화와 공원을 보고, 오후에는 서문정으로 돌아와 쇼핑과 저녁을 여유 있게 선택합니다.',
            planHeadline: '날씨가 좋으면 공원, 비가 오면 실내 박물관을 선택합니다.',
            planNote: '대안을 같은 시간대에 적어 두면 현장에서 일정을 다시 만들지 않아도 됩니다.',
            closingHeadline: '저녁은 서문정에서 두 시간 안에 끝냅니다.',
            closingNote: '긴 이동을 추가하지 않고 숙소로 돌아가 휴식 시간을 확보합니다.',
            morningSummary: '베이터우 공원·온천박물관',
            afternoonSummary: '서문정 산책·쇼핑',
            eveningSummary: '저녁·휴식',
            facts: [],
            routes: [
                {
                    origin: '숙소',
                    destination: '베이터우',
                    minutes: 50,
                    pathText: '중산역권 → 베이터우 환승 → 공원',
                    formula: '승차 30분 + 환승·역 접근 20분의 계획값',
                },
                {
                    origin: '베이터우',
                    destination: '서문정',
                    minutes: 45,
                    pathText: '베이터우 → 도심 환승 → 서문정',
                    formula: '승차·환승·점심 여유를 포함한 계획값',
                },
                {
                    origin: '서문정',
                    destination: '숙소',
                    minutes: 25,
                    pathText: '서문정 → 중산역권',
                    formula: '도보와 대중교통을 포함한 복귀 계획값',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '08:30~09:20',
                    title: '숙소 → 베이터우 이동',
                    kind: 'planned',
                    note: '아침 혼잡을 고려한 계획값',
                    bufferNote: '환승 여유 15분',
                    mapQuery: 'Beitou Park Taipei',
                },
                {
                    timeLabel: '09:20~10:30',
                    title: '베이터우 공원·온천박물관',
                    kind: 'target',
                    note: '운영일과 관람 조건은 공식 안내 확인',
                    bufferNote: '다음 장소 이동 전 15분',
                    mapQuery: 'Beitou Hot Spring Museum',
                },
                {
                    timeLabel: '10:30~11:30',
                    title: '지열곡 또는 실내 대안',
                    kind: 'flexible',
                    note: '날씨·컨디션에 따라 공원 산책이나 카페로 대체',
                    bufferNote: '도심 이동 여유',
                    mapQuery: 'Thermal Valley Beitou',
                },
                {
                    timeLabel: '11:30~12:30',
                    title: '베이터우 점심',
                    kind: 'flexible',
                    note: '식사 시간을 길게 잡지 않고 다음 구역으로 이동',
                    bufferNote: null,
                    mapQuery: 'Beitou Taipei',
                },
                {
                    timeLabel: '12:30~13:30',
                    title: '베이터우 → 서문정 이동',
                    kind: 'planned',
                    note: '환승역에서 다음 승강장을 미리 확인',
                    bufferNote: '환승 여유 20분',
                    mapQuery: 'Ximen Station Taipei',
                },
                {
                    timeLabel: '13:30~16:30',
                    title: '서문정 거리 산책·상점',
                    kind: 'planned',
                    note: '쇼핑 목록을 먼저 정하고 자유 시간을 남김',
                    bufferNote: '저녁 전 20분 여유',
                    mapQuery: 'Ximending Taipei',
                },
                {
                    timeLabel: '16:30~18:30',
                    title: '서문정 저녁',
                    kind: 'flexible',
                    note: '대기시간이 길면 근처 대안으로 전환',
                    bufferNote: null,
                    mapQuery: 'Ximending Taipei',
                },
                {
                    timeLabel: '18:30 이후',
                    title: '숙소 복귀·휴식',
                    kind: 'planned',
                    note: '근교 이동일을 앞두고 일찍 마무리',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
            ],
            notes: [
                {
                    leading: '베이터우의 운영·휴관 정보는 기관별로 다릅니다. ',
                    linkLabel: '타이베이 공식 여행 안내',
                    linkUrl: 'https://www.travel.taipei/en',
                    trailing: '에서 장소를 선택한 뒤 공식 페이지로 이동하세요.',
                },
            ],
        },
        {
            date: '2026-11-08',
            shortLabel: '근교',
            title: '지우펀·스펀 근교 하루',
            subtitle: '11/8 일 · 이동 버퍼를 크게 둔 근교 일정',
            overview: '지우펀과 스펀을 한 번에 욕심내지 않도록 이동·대기 시간을 넉넉히 두고, 귀환 시각을 고정하지 않는 날입니다.',
            planHeadline: '근교일은 방문 순서보다 귀환 버퍼가 우선입니다.',
            planNote: '교통 상황에 따라 스펀을 생략하고 지우펀 체류를 늘릴 수 있게 두 장소의 우선순위를 적어 둡니다.',
            closingHeadline: '타이베이 복귀 후에는 일정 없이 저녁을 둡니다.',
            closingNote: '돌아오는 시각을 약속으로 잡지 않고 숙소 근처 식사와 휴식으로 마무리합니다.',
            morningSummary: '타이베이 → 지우펀',
            afternoonSummary: '스펀 또는 지우펀 여유',
            eveningSummary: '타이베이 복귀·저녁',
            facts: [
                { label: '우선순위', value: '1 지우펀 체류 · 2 스펀 추가' },
                { label: '운영 원칙', value: '특정 버스·열차 시각을 확정하지 않고 당일 안내를 따름' },
            ],
            routes: [
                {
                    origin: '타이베이',
                    destination: '지우펀',
                    minutes: 90,
                    pathText: '도시역 → 북부 근교 교통 → 지우펀',
                    formula: '승차·환승 60분 + 정류장 대기·산길 접근 30분의 계획값',
                },
                {
                    origin: '지우펀',
                    destination: '스펀',
                    minutes: 60,
                    pathText: '지우펀 → 근교 환승 → 스펀',
                    formula: '교통 연결을 당일 확인하고 60분을 상한 계획으로 사용',
                },
                {
                    origin: '스펀 또는 지우펀',
                    destination: '타이베이 숙소',
                    minutes: 120,
                    pathText: '근교 정류장 → 타이베이 도심 → 숙소',
                    formula: '귀환 승차·환승·혼잡 버퍼를 크게 잡은 계획값',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '08:00~08:30',
                    title: '아침 식사·근교 준비',
                    kind: 'flexible',
                    note: '우천 시 미끄럼 방지 신발과 겉옷 확인',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
                {
                    timeLabel: '08:30~10:00',
                    title: '타이베이 → 지우펀 이동',
                    kind: 'planned',
                    note: '특정 출발 시각이 아닌 계획 구간',
                    bufferNote: '환승·대기 30분 포함',
                    mapQuery: 'Jiufen Old Street',
                },
                {
                    timeLabel: '10:00~12:30',
                    title: '지우펀 골목·전망대',
                    kind: 'planned',
                    note: '계단과 경사를 고려해 한 구역씩 이동',
                    bufferNote: '점심 전 20분 여유',
                    mapQuery: 'Jiufen Old Street Taiwan',
                },
                {
                    timeLabel: '12:30~13:30',
                    title: '지우펀 점심',
                    kind: 'flexible',
                    note: '대기열이 길면 간단한 식사로 전환',
                    bufferNote: null,
                    mapQuery: 'Jiufen Old Street Taiwan',
                },
                {
                    timeLabel: '13:30~14:30',
                    title: '스펀 이동 또는 지우펀 연장',
                    kind: 'flexible',
                    note: '컨디션·교통에 따라 두 선택지 중 하나를 유지',
                    bufferNote: '근교 연결 버퍼',
                    mapQuery: 'Shifen Old Street Taiwan',
                },
                {
                    timeLabel: '14:30~16:00',
                    title: '스펀 폭포·거리 또는 카페',
                    kind: 'target',
                    note: '운영·혼잡·우천 여부에 따라 한 장소만 선택',
                    bufferNote: '귀환 준비 20분',
                    mapQuery: 'Shifen Waterfall',
                },
                {
                    timeLabel: '16:00~18:00',
                    title: '타이베이로 귀환',
                    kind: 'planned',
                    note: '귀환 시각은 범위로만 보고 특정 약속을 두지 않음',
                    bufferNote: '교통 지연 대응 30분',
                    mapQuery: 'Taipei Main Station',
                },
                {
                    timeLabel: '18:00 이후',
                    title: '숙소 근처 저녁·휴식',
                    kind: 'flexible',
                    note: '근교일의 피로에 맞춰 외출을 생략할 수 있음',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
            ],
            notes: [
                {
                    leading: '지우펀·스펀 이동은 날씨와 현장 혼잡의 영향을 크게 받습니다. ',
                    linkLabel: '대만 관광청 공식 안내',
                    linkUrl: 'https://eng.taiwan.net.tw/',
                    trailing: '와 현지 교통 안내를 출발 전에 확인하세요.',
                },
                { leading: '근교일은 한 장소를 생략해도 완성되는 구조로 작성했습니다.', linkLabel: null, linkUrl: null, trailing: null },
            ],
        },
        {
            date: '2026-11-09',
            shortLabel: '귀국',
            title: '타이베이 101과 공항 이동',
            subtitle: '11/9 월 · TPE 18:30 출발 예시',
            overview: '체크아웃 후 숙소에 짐을 맡기고 한 곳만 방문한 뒤, 공항 도착 버퍼를 충분히 확보해 귀국합니다.',
            planHeadline: '귀국일은 공항 이동 시각을 먼저 고정합니다.',
            planNote: '타이베이 101 방문을 줄이거나 생략해도 공항 계획이 흔들리지 않도록 오후에 넉넉한 공백을 둡니다.',
            closingHeadline: '공항에서는 체크인보다 식사와 대기를 먼저 준비합니다.',
            closingNote: '실제 항공사 마감 시각과 터미널 안내가 이 모델 일정의 모든 계획값보다 우선합니다.',
            morningSummary: '체크아웃·타이베이 101',
            afternoonSummary: '숙소 → 공항·출국 준비',
            eveningSummary: '귀국 항공 이동',
            facts: [
                { label: '체크아웃', value: '11:00 예시, 실제 숙소 조건 확인' },
                { label: '공항 도착 목표', value: '출발 2시간 30분 전을 계획값으로 사용' },
                { label: '귀국 공항', value: '타오위안(TPE), 터미널은 항공사 안내 확인' },
            ],
            routes: [
                {
                    origin: '숙소',
                    destination: '타이베이 101',
                    minutes: 35,
                    pathText: '짐 보관 → 도심 대중교통 → 타이베이 101',
                    formula: '승차·환승·입구 접근을 포함한 계획값',
                },
                {
                    origin: '타이베이 101',
                    destination: '타오위안공항',
                    minutes: 100,
                    pathText: '타이베이 101 → 타이베이역권 → 공항 교통',
                    formula: '도심 복귀 35분 + 공항 이동 65분의 계획값',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '08:00~09:00',
                    title: '아침 식사·짐 정리',
                    kind: 'flexible',
                    note: '여권·귀국 항공 정보를 별도로 확인',
                    bufferNote: null,
                    mapQuery: 'Zhongshan Station Taipei',
                },
                {
                    timeLabel: '09:00~10:00',
                    title: '체크아웃·짐 보관',
                    kind: 'planned',
                    note: '숙소에 짐을 맡길 수 있는지 전날 확인',
                    bufferNote: '출발 전 20분 여유',
                    mapQuery: 'Zhongshan Station Taipei',
                },
                {
                    timeLabel: '10:00~12:00',
                    title: '타이베이 101 전망대 목표',
                    kind: 'target',
                    note: '운영·입장 조건은 공식 사이트에서 확인. 부담되면 주변 산책으로 대체',
                    bufferNote: '점심 전 20분 여유',
                    mapQuery: 'Taipei 101 Observatory',
                },
                {
                    timeLabel: '12:00~13:00',
                    title: '타이베이 101 주변 점심',
                    kind: 'flexible',
                    note: '공항 이동 전 가볍게 식사',
                    bufferNote: null,
                    mapQuery: 'Taipei 101 Mall',
                },
                {
                    timeLabel: '13:00~14:40',
                    title: '숙소 복귀·짐 수령·공항 이동',
                    kind: 'planned',
                    note: '도심 교통과 공항 이동을 합친 계획 구간',
                    bufferNote: '지연 대응 30분',
                    mapQuery: 'Taoyuan International Airport Terminal 1',
                },
                {
                    timeLabel: '14:40~16:30',
                    title: '공항 체크인·보안검색·출국심사',
                    kind: 'planned',
                    note: '실제 항공사 마감 시각과 터미널 안내 우선',
                    bufferNote: '탑승 전 30분 여유',
                    mapQuery: 'Taoyuan International Airport Terminal 1',
                },
                {
                    timeLabel: '16:30~18:20',
                    title: '공항 식사·탑승 대기',
                    kind: 'flexible',
                    note: '게이트 변경과 이동을 고려해 일찍 대기',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '18:30~22:00',
                    title: '타오위안공항 → 인천공항',
                    kind: 'confirmed',
                    note: '예시 항공 구간. 실제 운항·편명·터미널은 예약 시 확인',
                    bufferNote: null,
                    mapQuery: null,
                },
            ],
            notes: [
                {
                    leading: '타이베이 101의 입장·운영 정보는 ',
                    linkLabel: '공식 사이트',
                    linkUrl: 'https://www.taipei-101.com.tw/en/',
                    trailing: '에서 확인하고, 시간이 부족하면 방문을 생략합니다.',
                },
            ],
        },
    ],
    bookings: [
        {
            title: '왕복 항공권·여권 정보',
            whenLabel: '출발 전',
            priority: 'p1',
            linkLabel: '타오위안공항 공식 안내',
            linkUrl: 'https://www.taoyuan-airport.com/english',
            actionNote: '편명·터미널·수하물 조건을 예약 내역과 함께 확인',
            planStatus: '예시 데이터 · 예약 전',
            attachments: [{ kind: 'link', url: 'https://www.taoyuan-airport.com/english', label: '공항 안내' }],
        },
        {
            title: '중산역 인근 숙소',
            whenLabel: '출발 전',
            priority: 'p1',
            linkLabel: '숙소 위치 예시 지도',
            linkUrl: 'https://www.google.com/maps/search/?api=1&query=Zhongshan+Station+Taipei+hotel',
            actionNote: '실제 숙소를 예약한 뒤 주소·체크인·짐 보관 조건으로 교체',
            planStatus: '예시 데이터 · 예약 전',
            attachments: [],
        },
        {
            title: '국립고궁박물관',
            whenLabel: '11/6 오전 목표',
            priority: 'p2',
            linkLabel: '공식 관람 안내',
            linkUrl: 'https://www.npm.gov.tw/?l=2',
            actionNote: '전시·휴관·입장 조건을 출발 전 확인',
            planStatus: '목표 일정 · 미확정',
            attachments: [{ kind: 'link', url: 'https://www.npm.gov.tw/?l=2', label: '공식 사이트' }],
        },
        {
            title: '타이베이 101 전망대',
            whenLabel: '11/9 오전 목표',
            priority: 'p2',
            linkLabel: '공식 방문 안내',
            linkUrl: 'https://www.taipei-101.com.tw/en/',
            actionNote: '귀국일 공항 이동을 우선하고 필요하면 생략',
            planStatus: '목표 일정 · 미확정',
            attachments: [],
        },
        {
            title: '지우펀·스펀 근교 이동',
            whenLabel: '11/8',
            priority: 'p2',
            linkLabel: '대만 관광청 공식 안내',
            linkUrl: 'https://eng.taiwan.net.tw/',
            actionNote: '당일 날씨·교통·혼잡에 맞춰 한 장소를 생략할 수 있음',
            planStatus: '현장 판단',
            attachments: [],
        },
        {
            title: '공항 MRT·도시 교통',
            whenLabel: '도착일·귀국일',
            priority: 'p3',
            linkLabel: '공항 MRT 안내',
            linkUrl: 'https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/',
            actionNote: '실제 터미널과 운행 상태를 확인해 경로 선택',
            planStatus: '경로 확인',
            attachments: [],
        },
        {
            title: '저녁 식사 후보',
            whenLabel: '매일 저녁',
            priority: 'p3',
            linkLabel: '타이베이 공식 여행 안내',
            linkUrl: 'https://www.travel.taipei/en',
            actionNote: '예약이 필요한 곳만 별도 예약하고 나머지는 현장 선택',
            planStatus: '후보 목록',
            attachments: [],
        },
        {
            title: '여권·eSIM·우천 준비물',
            whenLabel: '출발 전날',
            priority: 'onsite',
            linkLabel: null,
            linkUrl: null,
            actionNote: '작은 우산, 편한 신발, 보조 배터리, 여권 사본을 확인',
            planStatus: '체크리스트',
            attachments: [],
        },
    ],
    infoSections: [
        {
            title: '이 모델 일정의 사용법',
            isDefaultOpen: true,
            blocks: [
                {
                    kind: 'paragraph',
                    emphasis: '핵심 원칙',
                    text: '하루에 핵심 방문 1~2곳만 두고, 식사·휴식·귀환을 실제 일정으로 기록했습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '확정 시각은 항공처럼 바뀌면 영향이 큰 항목에만 사용합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                { kind: 'bullet', emphasis: null, text: '여유 일정은 현장에서 줄이거나 대체할 수 있는 항목입니다.', linkLabel: null, linkUrl: null },
                { kind: 'bullet', emphasis: null, text: '모든 이동시간은 계획값이며 실제 안내와 다를 수 있습니다.', linkLabel: null, linkUrl: null },
            ],
        },
        {
            title: '이동·공항 기준',
            isDefaultOpen: false,
            blocks: [
                { kind: 'heading', emphasis: '출발 전 확인', text: '공식 안내 우선', linkLabel: null, linkUrl: null },
                {
                    kind: 'paragraph',
                    emphasis: null,
                    text: '항공사, 공항, 관광지의 최신 운영 조건을 확인한 뒤 계획 시각과 링크를 실제 값으로 바꿉니다.',
                    linkLabel: '타오위안공항 공식 안내',
                    linkUrl: 'https://www.taoyuan-airport.com/english',
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '공항 이동은 도착·출발 터미널이 확정된 뒤 경로를 선택합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '근교 이동은 귀환 버퍼를 먼저 확보하고 특정 시각 약속을 최소화합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
            ],
        },
        {
            title: '전체 일정 요약',
            isDefaultOpen: false,
            blocks: [{ kind: 'day_table', emphasis: null, text: null, linkLabel: null, linkUrl: null }],
        },
        {
            title: '준비물과 대안',
            isDefaultOpen: false,
            blocks: [
                {
                    kind: 'paragraph',
                    emphasis: '우천 대안',
                    text: '베이터우 공원과 근교 산책은 실내 관람·카페로 바꿀 수 있도록 비워 둡니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '여권·항공 정보·숙소 주소를 오프라인에서도 확인할 수 있게 저장합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '편한 신발, 작은 우산, 보조 배터리, 여벌 양말을 준비합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
            ],
        },
    ],
} as const satisfies TripTemplateInput

export type ModelExampleTripTemplate = typeof MODEL_EXAMPLE_TRIP_TEMPLATE
