import type { TripTemplateInput } from '@/shared/lib/trip-template'

export const OSAKA_TRIP_TEMPLATE = {
    title: '오사카 여행 노트',
    eyebrow: 'KANSAI / OCTOBER 2026',
    destination: '오사카',
    startDate: '2026-10-01',
    endDate: '2026-10-07',
    periodNote: '6박 7일 · 예비일 하루',
    disclaimer: '항공편·셔틀 외 시각은 계획값입니다.',
    verifiedOn: '2026-09-09',
    bufferPolicy: '일반 일정은 표시 구간의 마지막 10분, 항공편·공식 셔틀은 인접 대기 구간에서 10분을 확보합니다.',
    bookingNote: '키린과 아사히 회차를 먼저 확보한 뒤 나머지 입장권을 구매합니다.',
    footerNote: '최신 합의 일정을 기준으로 작성했습니다. 개별 열차 연결과 투어 잔여석은 미확정입니다. 공식 예매 링크는 인터넷 연결이 필요합니다.',
    flights: [
        {
            direction: 'outbound',
            label: '10.01 목 · 출국',
            departCode: 'ICN',
            departTime: '16:10',
            departTerminal: 'T2',
            arriveCode: 'KIX',
            arriveTime: '18:05',
            arriveTerminal: 'T1',
            flightNumber: null,
            note: null,
        },
        {
            direction: 'inbound',
            label: '10.07 수 · 귀국',
            departCode: 'KIX',
            departTime: '11:10',
            departTerminal: 'T1',
            arriveCode: 'ICN',
            arriveTime: '13:00',
            arriveTerminal: 'T2',
            flightNumber: null,
            note: null,
        },
    ],
    lodgings: [
        {
            name: '토요코인 오사카 신사이바시 니시',
            nameLocal: '東横INN大阪心斎橋西 / Toyoko Inn Osaka Shinsaibashi Nishi',
            address: '大阪府大阪市西区北堀江1-9-22',
            accessNote: '요츠바시역 4번 출구 도보 1분',
            checkIn: '15:00',
            checkOut: '10:00',
            url: 'https://www.toyoko-inn.com/search/detail/00023/',
            note: '조식 06:30~09:00',
        },
    ],
    days: [
        {
            date: '2026-10-01',
            shortLabel: '도착',
            title: '칸사이 도착',
            subtitle: '10/1 목 · ICN T2 16:10 · KIX T1 18:05',
            overview: '인천공항 제2터미널 → 칸사이공항 → 숙소 체크인 → 숙소 근처 저녁.',
            planHeadline: '칸사이공항 제1터미널 → 난카이 공항급행 → 난바 → 택시 → 숙소',
            planNote:
                '를 기본으로 잡습니다. 짐이 있는 도착일이라 난바에서 지하철 환승 대신 택시를 이용하는 제안이며, 교통상황에 따라 시간이 달라집니다.',
            closingHeadline: '숙소 도착은 20:30~21:30 정도를 계획 범위로 두고, 기본 시간표는21:00 도착으로 잡습니다.',
            closingNote:
                '이는 보장 범위가 아니며 항공편 지연·입국 혼잡 시 더 늦어질 수 있습니다. 계산은18:05 + 75분 + 25분 + 50분 + 25분 = 21:00입니다.',
            morningSummary: '항공 이동',
            afternoonSummary: '항공 이동',
            eveningSummary: '체크인·숙소 근처 식사',
            facts: [
                {
                    label: '출발 공항',
                    value: '서울/인천(ICN), 제2터미널',
                },
                {
                    label: '출발 일시',
                    value: '2026년 10월 1일(목) 16:10',
                },
                {
                    label: '도착 공항',
                    value: '오사카/칸사이(KIX)',
                },
                {
                    label: '도착 일자',
                    value: '2026년 10월 1일(목)',
                },
                {
                    label: '도착 시각·터미널',
                    value: '18:05, 제1터미널',
                },
                {
                    label: '항공사·편명',
                    value: '미제공',
                },
            ],
            routes: [],
            scheduleItems: [
                {
                    timeLabel: '16:10~18:05',
                    title: '인천 제2터미널 → 칸사이 제1터미널',
                    kind: 'confirmed',
                    note: '사용자 제공 항공 일정, 1시간55분',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '18:05~19:20',
                    title: '하기·입국심사·수하물·세관',
                    kind: 'planned',
                    note: '계획상75분, 실제 대기에 따라 변동',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '19:20~19:45',
                    title: '2층 연결통로로 난카이 칸사이공항역 이동·발권·대기',
                    kind: 'planned',
                    note: '25분 배정',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '19:45~20:35',
                    title: '난카이 공항급행으로 난바 이동',
                    kind: 'planned',
                    note: '약45~50분, 50분 배정. 19:45는 실제 열차 출발시각이 아닌 계획값',
                    bufferNote: null,
                    mapQuery: 'Nankai Namba Station',
                },
                {
                    timeLabel: '20:35~21:00',
                    title: '난바역 하차·택시 승차·숙소 이동',
                    kind: 'planned',
                    note: '역 출구·택시 대기15분 + 주행10분, 총25분 계획',
                    bufferNote: null,
                    mapQuery: 'Toyoko Inn Osaka Shinsaibashi Nishi',
                },
                {
                    timeLabel: '21:00 전후',
                    title: '체크인',
                    kind: 'planned',
                    note: '입국 수속이 빠르면 앞당겨짐',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '체크인 후',
                    title: '숙소 근처 저녁',
                    kind: 'planned',
                    note: '관광 예약 없음',
                    bufferNote: null,
                    mapQuery: null,
                },
            ],
            notes: [
                {
                    leading: '제1터미널은 2층에서 공항역으로 연결됩니다.',
                    linkLabel: '칸사이공항 공식 철도 접근',
                    linkUrl: 'https://www.kansai-airport.or.jp/access/to-airport/train',
                    trailing: null,
                },
                {
                    leading: null,
                    linkLabel: '난카이 공항 접근·열차 안내',
                    linkUrl: 'https://www.nankai.co.jp/traffic/kix.html',
                    trailing:
                        ': 공항급행 기본, 짐을 편하게 두고 지정석을 원하면 라피트 대체 가능. 라피트는 최단34분이지만 대기시간까지 포함해 다음 출발편을 비교합니다.',
                },
                {
                    leading: null,
                    linkLabel: '라피트 공식 안내·구매 입구',
                    linkUrl: 'https://www.nankai.co.jp/traffic/express/rapit.html',
                    trailing: ': 도착 수속 종료시각이 불확실하므로 특정 편은 실제 탑승 가능한 시간에 맞춰 선택합니다.',
                },
                {
                    leading: null,
                    linkLabel: '칸사이공항역 공식 시각표',
                    linkUrl: 'https://www.nankai.co.jp/traffic/station/kansaiairport.html',
                    trailing: ': 난바 방면 평일 시각표 확인.',
                },
                {
                    leading: '택시 대신 난바에서 숙소까지 걷는 경우 짐 포함 약25~35분을 계획합니다. 이 보행시간은 추정값입니다.',
                    linkLabel: null,
                    linkUrl: null,
                    trailing: null,
                },
            ],
        },
        {
            date: '2026-10-02',
            shortLabel: '히메지·코베',
            title: '히메지 · 키린 · 코베',
            subtitle: '10/2 금 · 산다역 14:30 셔틀 · 견학 15:10 목표',
            overview:
                '히메지성 → JR 히메지 → 아마가사키 환승 → JR 산다 → 키린공장으로 이동합니다. 코베 시내에는 들르지 않으며, 코베 방문은 공장 견학 후 야경·저녁으로 모읍니다. 직통 열차가 있다는 뜻은 아니며 아마가사키에서 환승합니다.',
            planHeadline: '14:15까지 산다역 셔틀 승차장 도착, 14:30 셔틀 탑승',
            planNote:
                '을 기준으로 잡습니다. 점심은 환승 목적지인 산다역 근처에서 먹습니다. 14:50 공장 도착 후에는15:10 견학 전 식사시간이 부족하므로 공장 레스토랑 점심은 넣지 않습니다.',
            closingHeadline: null,
            closingNote:
                '히메지~산다는 조회된 다른 날짜의 JR 경로에서 약1시간32분~1시간39분이므로, 역간 이동에100분을 배정했습니다. 실제10/2 출발편은 미확정입니다. 아마가사키에서는 산다에 정차하는 JR 타카라즈카선 열차를 선택합니다.\n\n공장 견학 후 코베로 갈 때는 산다 → 타니가미(谷上) → 산노미야 경로를 이용합니다. 코베전철·지하철 연결은 출발 전 다시 조회해야 합니다.\n\n셔틀은 예약제가 아니며 만석이면 탑승할 수 없습니다. 14:30편을 놓치면 예정 투어에 맞추기 어렵습니다. 산다 도착이 늦으면 점심을 간단히 하고 셔틀 승차를 우선합니다. 15:10 회차가 없거나 만석이면 이 날짜의 키린공장을 확정하지 말고 예비일 가능 회차를 검토합니다.',
            morningSummary: '히메지성',
            afternoonSummary: '산다역 경유 → 키린 코베공장',
            eveningSummary: '포트타워·항구 야경·저녁',
            facts: [],
            routes: [
                {
                    origin: '숙소',
                    destination: '히메지성',
                    minutes: 110,
                    pathText: '요츠바시 → 니시우메다, JR 오사카 → 히메지 신쾌속, 성까지 도보',
                    formula: '승차 약70분 + 숙소·역 출입·오사카 환승·성 접근 도보30분 + 대기·여유10분',
                },
                {
                    origin: '히메지성',
                    destination: 'JR 산다역',
                    minutes: 130,
                    pathText: 'JR 히메지 → 신쾌속 아마가사키(尼崎) → JR 타카라즈카선 산다(三田)',
                    formula: '성~히메지역 도보20분 + 역간 약100분(아마가사키 환승 포함) + 출발대기·역 출입10분',
                },
                {
                    origin: '산다',
                    destination: '키린공장',
                    minutes: 20,
                    pathText: '무료 라가버스',
                    formula: '14:30 출발, 14:50 도착',
                },
                {
                    origin: '공장',
                    destination: '산다',
                    minutes: 20,
                    pathText: '무료 라가버스',
                    formula: '16:40 출발, 17:00 도착',
                },
                {
                    origin: '산다',
                    destination: '포트타워',
                    minutes: 90,
                    pathText: '산다 → 타니가미 → 산노미야, 항구까지 도보',
                    formula: '열차 약45분 + 환승·대기15분 + 항구 접근 도보30분',
                },
                {
                    origin: '항구',
                    destination: '숙소',
                    minutes: 75,
                    pathText: 'JR 모토마치 → 오사카, 니시우메다 → 요츠바시',
                    formula: '승차 약35분 + 항구~역·오사카 환승·숙소 도보25분 + 대기15분',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '06:30~06:50',
                    title: '숙소 조식',
                    kind: 'planned',
                    note: '장거리 이동일',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '06:55~08:45',
                    title: '숙소 → 히메지성',
                    kind: 'planned',
                    note: '110분 배정',
                    bufferNote: null,
                    mapQuery: 'Himeji Castle',
                },
                {
                    timeLabel: '08:45~09:00',
                    title: '입장 준비',
                    kind: 'planned',
                    note: '개장 대기',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '09:00~11:00',
                    title: '히메지성',
                    kind: 'planned',
                    note: '2시간, 코코엔 별도 관람 제외',
                    bufferNote: null,
                    mapQuery: 'Himeji Castle',
                },
                {
                    timeLabel: '11:00~13:10',
                    title: '히메지성 → JR 히메지 → 아마가사키 → JR 산다',
                    kind: 'planned',
                    note: '130분 배정, 코베 시내 방문 없음',
                    bufferNote: null,
                    mapQuery: 'Sanda Station Hyogo',
                },
                {
                    timeLabel: '13:10~14:00',
                    title: '산다역 근처 점심',
                    kind: 'planned',
                    note: '식당 왕복 접근시간 포함50분, 혼잡하면 간단한 식사',
                    bufferNote: null,
                    mapQuery: 'Sanda Station Hyogo',
                },
                {
                    timeLabel: '14:00~14:15',
                    title: '산다역 셔틀 승차장 이동·확인',
                    kind: 'planned',
                    note: '식사 지연 여유 포함',
                    bufferNote: null,
                    mapQuery: 'Sanda Station Hyogo',
                },
                {
                    timeLabel: '14:15~14:30',
                    title: '셔틀 대기',
                    kind: 'planned',
                    note: '승차장 확인·줄 서기',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '14:30~14:50',
                    title: '산다역 → 키린공장 무료 셔틀',
                    kind: 'confirmed',
                    note: '공식 게시 시각',
                    bufferNote: null,
                    mapQuery: 'Kirin Beer Kobe Factory',
                },
                {
                    timeLabel: '14:50~15:10',
                    title: '접수·대기',
                    kind: 'target',
                    note: '목표 회차 전 20분',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '15:10~16:20',
                    title: '키린 견학·시음 목표',
                    kind: 'target',
                    note: '해당 날짜 회차·잔여석 확인 필요',
                    bufferNote: null,
                    mapQuery: 'Kirin Beer Kobe Factory',
                },
                {
                    timeLabel: '16:20~16:40',
                    title: '숍·셔틀 대기',
                    kind: 'planned',
                    note: '16:40 귀환편 탑승',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '16:40~17:00',
                    title: '키린공장 → 산다역 무료 셔틀',
                    kind: 'confirmed',
                    note: '공식 게시 시각',
                    bufferNote: null,
                    mapQuery: 'Sanda Station Hyogo',
                },
                {
                    timeLabel: '17:00~18:30',
                    title: '산다역 → 포트타워',
                    kind: 'planned',
                    note: '90분 배정',
                    bufferNote: null,
                    mapQuery: 'Kobe Port Tower',
                },
                {
                    timeLabel: '18:30~19:15',
                    title: '포트타워·항구 야경',
                    kind: 'target',
                    note: '탑에 올라갈 경우 18:30 이후 입장권 목표',
                    bufferNote: null,
                    mapQuery: 'Kobe Port Tower',
                },
                {
                    timeLabel: '19:15~20:15',
                    title: '저녁',
                    kind: 'planned',
                    note: '항구·모토마치 주변, 식당 위치에 따라 조정',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '20:15~21:30',
                    title: '숙소 복귀',
                    kind: 'planned',
                    note: '항구 출발 기준 75분 배정',
                    bufferNote: null,
                    mapQuery: 'Toyoko Inn Osaka Shinsaibashi Nishi',
                },
            ],
            notes: [
                {
                    leading: null,
                    linkLabel: '히메지성 공식 입장권 안내 — ‘しらさぎチケット’ 구매 링크',
                    linkUrl: 'https://www.city.himeji.lg.jp/castle/0000007671.html',
                    trailing: ': 10/2 09:00 목표. 디지털 티켓이 성 내부 대기까지 없애 주지는 않습니다.',
                },
                {
                    leading: null,
                    linkLabel: '키린 코베공장 공식 견학·예약 입구',
                    linkUrl: 'https://www.kirin.co.jp/experience/factory/kobe/event/is.html',
                    trailing: ': 10/2 15:10 일반 투어 목표. 약70분, 20세 이상 1,000엔(2026/10/1부터). 안내는 일본어입니다.',
                },
                {
                    leading: null,
                    linkLabel: '키린 무료 셔틀 시간표·승차장 지도',
                    linkUrl: 'https://www.kirin.co.jp/experience/factory/kobe/access/',
                    trailing: ': 산다역은 JR·코베전철 모두 접근 가능합니다.',
                },
                {
                    leading: null,
                    linkLabel: '포트타워 공식 티켓',
                    linkUrl: 'https://www.kobe-port-tower.com/ticket/',
                    trailing: ': 18:30 이후 목표. 전망층·옥상 입장 시 날짜·시간 지정권 필요. 외부 야경만 보면 입장권 불필요.',
                },
                {
                    leading: null,
                    linkLabel: '히메지~산다 JR 경로·소요시간 참고',
                    linkUrl: 'https://ekitan.com/transit/fare/sf-5884/st-5345',
                    trailing: ': 아마가사키 환승. 여행일과 출발시각을 변경해 조회합니다.',
                },
                {
                    leading: null,
                    linkLabel: '타니가미역 공식 정보·시각표',
                    linkUrl: 'https://www.shintetsu.co.jp/railway/station/tanigami/',
                    trailing: null,
                },
            ],
        },
        {
            date: '2026-10-03',
            shortLabel: '오사카',
            title: '카이유칸 · 별 · 야경',
            subtitle: '10/3 토 · 과학관은 플라네타리움만 관람',
            overview: null,
            planHeadline: null,
            planNote: null,
            closingHeadline: null,
            closingNote:
                '공식 안내의 오사카코역~카이유칸 도보는 약5분입니다. 표는 역 내부 이동과 입구 접근까지 더했습니다. 과학관~스카이빌딩은 도보만 이용할 수도 있지만, 이 표는 지하철 이용 기준입니다.',
            morningSummary: '카이유칸',
            afternoonSummary: '플라네타리움',
            eveningSummary: '우메다 하늘정원·저녁',
            facts: [],
            routes: [
                {
                    origin: '숙소',
                    destination: '카이유칸',
                    minutes: 40,
                    pathText: '요츠바시 → 혼마치 → 중앙선 오사카코',
                    formula: '열차 약12분 + 혼마치 환승5분 + 숙소·역 출입·수족관 접근13분 + 대기·여유10분',
                },
                {
                    origin: '텐포잔',
                    destination: '과학관',
                    minutes: 50,
                    pathText: '오사카코 → 혼마치 → 요츠바시선 히고바시',
                    formula: '열차 약13분 + 환승5분 + 역 출입·양쪽 시설 도보20분 + 대기·여유12분',
                },
                {
                    origin: '과학관',
                    destination: '스카이빌딩',
                    minutes: 40,
                    pathText: '히고바시 → 니시우메다 → 도보',
                    formula: '열차 약2분 + 양쪽 시설·역 도보28분 + 대기·여유10분',
                },
                {
                    origin: '스카이빌딩',
                    destination: '숙소',
                    minutes: 40,
                    pathText: '니시우메다 → 요츠바시',
                    formula: '열차 약7분 + 역까지·역 출입·숙소 도보23분 + 대기10분',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '09:00~09:40',
                    title: '숙소 → 카이유칸',
                    kind: 'planned',
                    note: '40분 배정',
                    bufferNote: null,
                    mapQuery: 'Osaka Aquarium Kaiyukan',
                },
                {
                    timeLabel: '09:40~10:00',
                    title: '입장 준비',
                    kind: 'planned',
                    note: '10시 입장이 가능한 날이라는 전제',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '10:00~13:00',
                    title: '카이유칸',
                    kind: 'planned',
                    note: '관람 3시간',
                    bufferNote: null,
                    mapQuery: 'Osaka Aquarium Kaiyukan',
                },
                {
                    timeLabel: '13:00~13:45',
                    title: '텐포잔 점심',
                    kind: 'planned',
                    note: '관람차·추가 관광 제외',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '13:45~14:35',
                    title: '과학관으로 이동',
                    kind: 'planned',
                    note: '50분 배정',
                    bufferNote: null,
                    mapQuery: 'Osaka Science Museum',
                },
                {
                    timeLabel: '14:35~15:00',
                    title: '입장 준비·대기',
                    kind: 'planned',
                    note: '늦으면 중간 입장 불가',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '15:00~15:45',
                    title: '플라네타리움 목표 회차',
                    kind: 'target',
                    note: '실제 10/3 프로그램·상영표 확인 필요',
                    bufferNote: null,
                    mapQuery: 'Osaka Science Museum',
                },
                {
                    timeLabel: '15:45~16:25',
                    title: '우메다 스카이빌딩으로 이동',
                    kind: 'planned',
                    note: '40분 배정',
                    bufferNote: null,
                    mapQuery: 'Umeda Sky Building',
                },
                {
                    timeLabel: '16:25~17:00',
                    title: '휴식·입장 준비',
                    kind: 'planned',
                    note: '혼잡 여유',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '17:00~18:30',
                    title: '우메다 하늘정원',
                    kind: 'planned',
                    note: '밝을 때부터 저녁 풍경까지',
                    bufferNote: null,
                    mapQuery: 'Umeda Sky Building',
                },
                {
                    timeLabel: '18:30~19:30',
                    title: '우메다 저녁',
                    kind: 'planned',
                    note: '자유',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '19:30~20:10',
                    title: '숙소 복귀',
                    kind: 'planned',
                    note: '스카이빌딩 주변 출발 기준 40분',
                    bufferNote: null,
                    mapQuery: 'Toyoko Inn Osaka Shinsaibashi Nishi',
                },
            ],
            notes: [
                {
                    leading: null,
                    linkLabel: '카이유칸 공식 e티켓 안내',
                    linkUrl: 'https://www.kaiyukan.com/info/ticket/',
                    trailing: ': 10/3 10시대 목표. 원칙적으로 30일 전부터 판매하므로 9/3부터 판매 범위입니다.',
                },
                {
                    leading: null,
                    linkLabel: '해당 날짜 운영시간 확인',
                    linkUrl: 'https://www.kaiyukan.com/info/hours/',
                    trailing: '. 당일 개장시간·티켓 슬롯을 확인한 뒤 확정합니다.',
                },
                {
                    leading: null,
                    linkLabel: '플라네타리움 공식 예매',
                    linkUrl: 'https://ticket.osaka.sci-museum.com/',
                    trailing: ': 10/3 15시대 목표. 9/26부터 구매 가능. ‘플라네타리움 단독권’을 선택합니다.',
                },
                {
                    leading: null,
                    linkLabel: '예매·취소 규정',
                    linkUrl: 'https://www.sci-museum.jp/info/webticket/',
                    trailing: '. 일반권은 관람 당일 08:55까지 취소 가능하며, 웹 판매는 개연 1시간 전까지입니다.',
                },
                {
                    leading: null,
                    linkLabel: '우메다 하늘정원 공식 티켓 안내',
                    linkUrl: 'https://www.skybldg.co.jp/observatory/information/',
                    trailing: ': 17시 전후 방문 목표. 공식 페이지의 WEB 티켓 구매로 이동합니다. 일반 운영시간은 09:30~22:30, 최종 입장22:00입니다.',
                },
                {
                    leading: null,
                    linkLabel: '스카이빌딩 공식 접근 안내',
                    linkUrl: 'https://www.skybldg.co.jp/access/',
                    trailing: null,
                },
                {
                    leading: null,
                    linkLabel: '요츠바시~오사카코 구간 운행 참고',
                    linkUrl: 'https://transit.yahoo.co.jp/search/result/大阪港-四ツ橋',
                    trailing: ': 검색 결과 예시는 반대 방향이며, 여행 당일 출발 방향·날짜를 바꿔 확인합니다.',
                },
            ],
        },
        {
            date: '2026-10-04',
            shortLabel: '나라',
            title: '나라',
            subtitle: '10/4 일 · 나라공원 · 토다이지 · 나라마치',
            overview: null,
            planHeadline: '나라공원·토다이지를 기본으로 하고, 오후는 가스가타이샤 또는 나라마치 중 하나를 선택합니다.',
            planNote: '아래는 나라마치 쪽으로 내려오는 기본안입니다.',
            closingHeadline: null,
            closingNote:
                '킨테츠나라역(近鉄奈良)을 사용합니다. JR 나라역과 다릅니다. 보통 급행·쾌속급행 기준이며 유료 특급 좌석은 이 일정의 전제가 아닙니다.',
            morningSummary: '나라공원·토다이지',
            afternoonSummary: '나라 관광',
            eveningSummary: '오사카 복귀',
            facts: [],
            routes: [
                {
                    origin: '숙소',
                    destination: '킨테츠나라',
                    minutes: 75,
                    pathText: '오사카난바역까지 도보 → 킨테츠 쾌속급행·급행',
                    formula: '숙소~승강장20분 + 승차 약40분 + 대기·도착역 출입15분',
                },
                {
                    origin: '킨테츠나라',
                    destination: '숙소',
                    minutes: 75,
                    pathText: '킨테츠 오사카난바 → 도보 귀환',
                    formula: '같은 기준',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '08:45~10:00',
                    title: '숙소 → 킨테츠나라역',
                    kind: 'planned',
                    note: '75분 배정',
                    bufferNote: null,
                    mapQuery: 'Kintetsu Nara Station',
                },
                {
                    timeLabel: '10:00~10:45',
                    title: '나라공원·사슴 구경',
                    kind: 'planned',
                    note: '토다이지 방향으로 이동',
                    bufferNote: null,
                    mapQuery: 'Nara Park',
                },
                {
                    timeLabel: '10:45~12:00',
                    title: '토다이지',
                    kind: 'planned',
                    note: '관람',
                    bufferNote: null,
                    mapQuery: 'Todai-ji',
                },
                {
                    timeLabel: '12:00~13:00',
                    title: '점심',
                    kind: 'planned',
                    note: '토다이지·공원 주변',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '13:00~14:00',
                    title: '코후쿠지·나라마치 방면 이동',
                    kind: 'planned',
                    note: '순수 보행 약30~40분, 휴식 여유 포함',
                    bufferNote: null,
                    mapQuery: 'Kofuku-ji',
                },
                {
                    timeLabel: '14:00~15:30',
                    title: '나라마치·카페',
                    kind: 'planned',
                    note: '가스가타이샤를 선택하면 이 구간과 대체',
                    bufferNote: null,
                    mapQuery: 'Naramachi',
                },
                {
                    timeLabel: '15:30~16:00',
                    title: '킨테츠나라역으로 이동',
                    kind: 'planned',
                    note: '출발 위치·가게 구경에 따라 조정',
                    bufferNote: null,
                    mapQuery: 'Kintetsu Nara Station',
                },
                {
                    timeLabel: '16:00~17:15',
                    title: '숙소 복귀',
                    kind: 'planned',
                    note: '75분 배정',
                    bufferNote: null,
                    mapQuery: 'Toyoko Inn Osaka Shinsaibashi Nishi',
                },
                {
                    timeLabel: '이후',
                    title: '저녁·휴식',
                    kind: 'planned',
                    note: '다음날 오전 투어 대비',
                    bufferNote: null,
                    mapQuery: null,
                },
            ],
            notes: [
                {
                    leading: null,
                    linkLabel: '나라 공식 교통 안내',
                    linkUrl: 'https://narashikanko.or.jp/lsc/upfile/pamphlet/0000/0042/42_201_file.pdf',
                    trailing: ': 오사카난바~킨테츠나라 약40분.',
                },
                {
                    leading:
                        '토다이지 등 유료 구역의 관람료는 현지에서 구매하는 방식으로 계획합니다. 나라 오후 세부 선택은 아직 고정하지 않았습니다.',
                    linkLabel: null,
                    linkUrl: null,
                    trailing: null,
                },
            ],
        },
        {
            date: '2026-10-05',
            shortLabel: '스이타',
            title: '아사히 · 태양의 탑 · 민족학박물관',
            subtitle: '10/5 월 · 공원 산책 없이 관람 중심',
            overview: null,
            planHeadline: '공원 산책 없이 세 시설만 관람합니다.',
            planNote: '태양의 탑은 공원 중앙입구 앞에 있어 큰 우회가 아닙니다. 박물관 관람시간을 우선 확보합니다.',
            closingHeadline: 'JR 스이타역과 한큐 스이타역은 별개입니다.',
            closingNote:
                '오전은 JR로 들어가고, 오후는 한큐로 나가도록 구성했습니다. 점심 식당이 동선에서 멀면 이동시간을 추가해야 합니다.\n\n태양의 탑 13시대 회차가 없거나 아사히 일정이 늦어지면, 탑 내부 관람을 빼고 박물관으로 바로 갑니다. 탑 외관 사진만 짧게 남기는 것은 가능하지만 공원·정원 산책은 추가하지 않습니다. 10월 세부 운영일과 선택 회차는 결제 화면에서 최종 확인합니다.',
            morningSummary: '아사히 맥주 뮤지엄',
            afternoonSummary: '태양의 탑 → 국립민족학박물관',
            eveningSummary: '저녁·숙소 복귀',
            facts: [],
            routes: [
                {
                    origin: '숙소',
                    destination: '아사히',
                    minutes: 60,
                    pathText: '요츠바시 → 니시우메다 → JR 오사카 → JR 스이타 → 도보',
                    formula: '열차7+9=16분 + 숙소·오사카 환승·JR 스이타~공장 도보24분 + 대기·여유20분',
                },
                {
                    origin: '아사히 부근',
                    destination: '태양의 탑',
                    minutes: 55,
                    pathText: '한큐 스이타 → 야마다 → 모노레일 만박기념공원 → 중앙입구 → 탑 접수처',
                    formula: '공장~한큐역10분 + 한큐10분 + 모노레일 약3분 + 야마다 환승·공원·탑 접근17분 + 대기15분',
                },
                {
                    origin: '태양의 탑',
                    destination: '박물관',
                    minutes: 15,
                    pathText: '공원 내 연결 보행로',
                    formula: '배치도 기반 보행 추정10~15분',
                },
                {
                    origin: '박물관',
                    destination: '숙소',
                    minutes: 80,
                    pathText: '만박기념공원역 → 센리추오 → 키타오사카급행·미도스지선 신사이바시 → 숙소',
                    formula: '모노레일·지하철 약35분 + 박물관~역·환승·숙소 도보30분 + 대기15분',
                },
            ],
            scheduleItems: [
                {
                    timeLabel: '08:40~09:40',
                    title: '숙소 → 아사히 뮤지엄',
                    kind: 'planned',
                    note: '60분 배정',
                    bufferNote: null,
                    mapQuery: 'Asahi Beer Museum Suita',
                },
                {
                    timeLabel: '09:40~10:00',
                    title: '접수·대기',
                    kind: 'target',
                    note: '10시 목표 회차 전 여유',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '10:00~11:30',
                    title: '아사히 견학·시음 목표',
                    kind: 'target',
                    note: '오전 회차 잔여석 확인 필요',
                    bufferNote: null,
                    mapQuery: 'Asahi Beer Museum Suita',
                },
                {
                    timeLabel: '11:30~12:15',
                    title: '점심',
                    kind: 'planned',
                    note: '뮤지엄·한큐 스이타역 인근',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '12:15~13:10',
                    title: '태양의 탑 접수처로 이동',
                    kind: 'planned',
                    note: '뮤지엄 부근 출발 기준 55분',
                    bufferNote: null,
                    mapQuery: 'Tower of the Sun Osaka',
                },
                {
                    timeLabel: '13:10~13:30',
                    title: '태양의 탑 접수·대기',
                    kind: 'planned',
                    note: '공식 안내: 예약20분 전 도착',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '13:30~14:00',
                    title: '태양의 탑 내부 관람 목표',
                    kind: 'target',
                    note: '약30분',
                    bufferNote: null,
                    mapQuery: 'Tower of the Sun Osaka',
                },
                {
                    timeLabel: '14:00~14:15',
                    title: '민족학박물관으로 이동',
                    kind: 'planned',
                    note: '도보15분 배정',
                    bufferNote: null,
                    mapQuery: 'National Museum of Ethnology Osaka',
                },
                {
                    timeLabel: '14:15~17:00',
                    title: '국립민족학박물관',
                    kind: 'planned',
                    note: '약2시간45분',
                    bufferNote: null,
                    mapQuery: 'National Museum of Ethnology Osaka',
                },
                {
                    timeLabel: '17:00~18:20',
                    title: '숙소 복귀',
                    kind: 'planned',
                    note: '80분 배정, 저녁을 먹고 오면 그만큼 뒤로 이동',
                    bufferNote: null,
                    mapQuery: 'Toyoko Inn Osaka Shinsaibashi Nishi',
                },
                {
                    timeLabel: '이후',
                    title: '저녁·휴식',
                    kind: 'planned',
                    note: '자유',
                    bufferNote: null,
                    mapQuery: null,
                },
            ],
            notes: [
                {
                    leading: null,
                    linkLabel: '아사히 공식 안내·예약 입구',
                    linkUrl: 'https://www.asahibeer.co.jp/brewery/suita/',
                    trailing:
                        ': 10/5 10:00 전후 목표. 공식 페이지에서 견학 예약으로 이동합니다. 공지상 10월 휴관일은 4·9·25일이며, 5일은 포함되지 않습니다. 예약 잔여석은 별도입니다.',
                },
                {
                    leading: null,
                    linkLabel: '아사히 공식 역·도보 지도',
                    linkUrl: 'https://www.asahibeer.co.jp/brewery/suita/access/',
                    trailing: null,
                },
                {
                    leading: null,
                    linkLabel: '태양의 탑 공식 예약 안내',
                    linkUrl: 'https://taiyounotou-expo70.jp/reserve/',
                    trailing:
                        ': 10/5 13:30 목표. 120일 앞까지 예약 가능하며, 전날까지 사전예약을 권장합니다. 결제 후 취소·환불 불가, 날짜 변경은 조건부 1회입니다.',
                },
                {
                    leading: null,
                    linkLabel: '공식 예약 사이트',
                    linkUrl: 'https://reserve.taiyounotou-expo70.jp/',
                    trailing: null,
                },
                {
                    leading: null,
                    linkLabel: '태양의 탑 내부 관람 안내',
                    linkUrl: 'https://taiyounotou-expo70.jp/guide/',
                    trailing: ': 약30분. 공원 입장 관련 요금이 포함되는지는 선택한 티켓 구성을 확인합니다.',
                },
                {
                    leading: null,
                    linkLabel: '국립민족학박물관 공식 관람·티켓 안내',
                    linkUrl: 'https://www.minpaku.ac.jp/information/basis',
                    trailing:
                        ': 10:00~17:00, 최종입장16:30, 통상 수요일 휴관. 상설전 중심으로 현장 구매 계획입니다. 태양의 탑 입장권 제시 할인 안내가 있으므로 티켓을 보관합니다.',
                },
                {
                    leading: null,
                    linkLabel: '공원·박물관 지역 공식 접근 안내',
                    linkUrl: 'https://www.expo70-park.jp/guide/access/',
                    trailing: null,
                },
                {
                    leading: null,
                    linkLabel: '한큐 스이타~야마다 표준 승차시간 참고',
                    linkUrl: 'https://ekitan.com/transit/route/sf-5460/st-6115',
                    trailing: ': 약10분.',
                },
                {
                    leading: null,
                    linkLabel: 'JR 오사카~스이타 표준 승차시간 출처',
                    linkUrl: 'https://www.city.suita.osaka.jp/suitablecity/1016975/1013138.html',
                    trailing: ': 약9분.',
                },
            ],
        },
        {
            date: '2026-10-06',
            shortLabel: '예비일',
            title: '비워 둔 하루',
            subtitle: '10/6 화 · 날씨와 예약 상황에 맞춰 사용',
            overview: '미리 관광을 채우지 않습니다. 비·예약 불가·컨디션으로 빠진 곳을 보완합니다.',
            planHeadline: null,
            planNote: null,
            closingHeadline: null,
            closingNote: null,
            morningSummary: '예비일',
            afternoonSummary: '예비일',
            eveningSummary: '자유',
            facts: [],
            routes: [],
            scheduleItems: [],
            notes: [
                {
                    leading: '키린이 10/2에 예약되지 않으면 10/6의 가능한 회차를 검토합니다.',
                    linkLabel: null,
                    linkUrl: null,
                    trailing: null,
                },
                {
                    leading: '우메다 야경을 날씨 때문에 못 봤으면 저녁에 재배치합니다.',
                    linkLabel: null,
                    linkUrl: null,
                    trailing: null,
                },
                {
                    leading: '예약 변경은 각 티켓 규정에 따릅니다. 특히 태양의 탑은 자유롭게 취소·환불하는 표가 아닙니다.',
                    linkLabel: null,
                    linkUrl: null,
                    trailing: null,
                },
            ],
        },
        {
            date: '2026-10-07',
            shortLabel: '귀국',
            title: '귀국',
            subtitle: '10/7 수 · 07:00 숙소 출발 · 08:40 공항 도착 목표',
            overview:
                '2026년 10월 7일(수) 칸사이(KIX) 제1터미널 11:10 출발 → 인천(ICN) 제2터미널 13:00 도착. 비행시간은 1시간50분입니다. 사용자 제공 항공 일정이며 항공사·편명은 미제공입니다.',
            planHeadline: '숙소에서 07:00 출발, 칸사이 제1터미널 08:40 도착을 목표',
            planNote:
                '로 잡습니다. 사용자 요청에 따라 출발 2시간 전인 09:10에서 여유 30분을 더 확보한 기준입니다. 항공사별 수속 마감시간을 확인한 값은 아닙니다.',
            closingHeadline: '계산: 07:00 + 택시15분 + 역 이동·대기20분 + 열차50분 + 터미널 이동15분 = 08:40.',
            closingNote:
                '07:35는 실제 열차 출발시각이 아닌 계획값입니다. 여행일 시각표에서 칸사이공항역 08:25 이전 도착편을 선택하고, 그 출발시각에 맞춰 난바 도착을 조정합니다.\n\n숙소 조식은 06:30부터 간단히 먹거나 공항에서 식사합니다. 공항 이동 외 관광은 넣지 않습니다. 택시는 전날 프런트에 07:00 승차 가능 여부를 확인하는 계획이며, 아직 예약하지 않았습니다.',
            morningSummary: '07:00 숙소 출발·11:10 칸사이 T1 출국',
            afternoonSummary: '13:00 인천 T2 도착',
            eveningSummary: null,
            facts: [],
            routes: [],
            scheduleItems: [
                {
                    timeLabel: '06:30~06:45',
                    title: '간단한 조식',
                    kind: 'planned',
                    note: '짐은 전날 정리',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '06:45~07:00',
                    title: '체크아웃·택시 승차 준비',
                    kind: 'target',
                    note: '07:00 출발 목표',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '07:00~07:15',
                    title: '숙소 → 난카이 난바역',
                    kind: 'planned',
                    note: '택시15분 배정, 교통에 따라 변동',
                    bufferNote: null,
                    mapQuery: 'Nankai Namba Station',
                },
                {
                    timeLabel: '07:15~07:35',
                    title: '난바역 발권·승강장 이동·열차 대기',
                    kind: 'planned',
                    note: '20분 배정',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '07:35~08:25',
                    title: '난카이 공항급행 → 칸사이공항역',
                    kind: 'planned',
                    note: '약45~50분, 50분 배정',
                    bufferNote: null,
                    mapQuery: 'Kansai International Airport Terminal 1',
                },
                {
                    timeLabel: '08:25~08:40',
                    title: '공항역 → 제1터미널 국제선 출발층',
                    kind: 'planned',
                    note: '연결통로·층 이동15분 배정',
                    bufferNote: null,
                    mapQuery: 'Kansai International Airport Terminal 1',
                },
                {
                    timeLabel: '08:40~탑승 안내시각',
                    title: '체크인·수하물·보안검색·출국심사',
                    kind: 'planned',
                    note: '항공사 카운터 개시 전이면 대기',
                    bufferNote: null,
                    mapQuery: null,
                },
                {
                    timeLabel: '11:10',
                    title: '칸사이 제1터미널 출발',
                    kind: 'confirmed',
                    note: '항공 일정',
                    bufferNote: null,
                    mapQuery: 'Kansai International Airport Terminal 1',
                },
                {
                    timeLabel: '13:00',
                    title: '인천 제2터미널 도착',
                    kind: 'confirmed',
                    note: '항공 일정',
                    bufferNote: null,
                    mapQuery: null,
                },
            ],
            notes: [
                {
                    leading: null,
                    linkLabel: '난카이 공식 공항 접근·시각표·티켓',
                    linkUrl: 'https://www.nankai.co.jp/traffic/kix.html',
                    trailing: null,
                },
                {
                    leading: null,
                    linkLabel: '라피트 공식 안내·구매',
                    linkUrl: 'https://www.nankai.co.jp/traffic/express/rapit.html',
                    trailing: ': 같은 도착 목표에 맞는 지정석 편이 있으면 대체 가능합니다. 별도 특급권 필요.',
                },
                {
                    leading: null,
                    linkLabel: '칸사이공항 철도 연결 안내',
                    linkUrl: 'https://www.kansai-airport.or.jp/access/to-airport/train',
                    trailing: ': 공항역은 제1터미널2층에 연결됩니다.',
                },
            ],
        },
    ],
    bookings: [
        {
            title: '키린 코베공장',
            whenLabel: '10/2 15:10 일반 투어',
            priority: 'p1',
            linkLabel: '공식 견학·예약',
            linkUrl: 'https://www.kirin.co.jp/experience/factory/kobe/event/is.html',
            actionNote: '지금 가능 회차 확인',
            planStatus: '미예약',
        },
        {
            title: '아사히 스이타',
            whenLabel: '10/5 10시대',
            priority: 'p1',
            linkLabel: '공식 예약 입구',
            linkUrl: 'https://www.asahibeer.co.jp/brewery/suita/',
            actionNote: '지금 확인',
            planStatus: '미예약',
        },
        {
            title: '태양의 탑',
            whenLabel: '10/5 13:30',
            priority: 'p2',
            linkLabel: '예약 규정·구매',
            linkUrl: 'https://taiyounotou-expo70.jp/reserve/',
            actionNote: '아사히 확정 후',
            planStatus: '미예약',
        },
        {
            title: '카이유칸',
            whenLabel: '10/3 10시대',
            priority: 'p2',
            linkLabel: '공식 e티켓',
            linkUrl: 'https://www.kaiyukan.com/info/ticket/',
            actionNote: '원칙상 9/3부터',
            planStatus: '미구매',
        },
        {
            title: '플라네타리움 단독',
            whenLabel: '10/3 15시대',
            priority: 'p2',
            linkLabel: '공식 예매',
            linkUrl: 'https://ticket.osaka.sci-museum.com/',
            actionNote: '9/26부터',
            planStatus: '판매 전',
        },
        {
            title: '히메지성',
            whenLabel: '10/2 09:00',
            priority: 'p3',
            linkLabel: '공식 티켓 안내',
            linkUrl: 'https://www.city.himeji.lg.jp/castle/0000007671.html',
            actionNote: '키린 확정 후',
            planStatus: '미구매',
        },
        {
            title: '포트타워',
            whenLabel: '10/2 18:30 이후',
            priority: 'p3',
            linkLabel: '공식 구매 안내',
            linkUrl: 'https://www.kobe-port-tower.com/ticket/',
            actionNote: '탑에 올라갈 경우',
            planStatus: '미구매',
        },
        {
            title: '우메다 하늘정원',
            whenLabel: '10/3 17시 전후',
            priority: 'p3',
            linkLabel: '공식 구매 안내',
            linkUrl: 'https://www.skybldg.co.jp/observatory/information/',
            actionNote: null,
            planStatus: '미구매',
        },
        {
            title: '민족학박물관',
            whenLabel: '10/5 14시대',
            priority: 'onsite',
            linkLabel: '관람료·구매 안내',
            linkUrl: 'https://www.minpaku.ac.jp/information/basis',
            actionNote: '태양의 탑 티켓 보관',
            planStatus: '현장 계획',
        },
    ],
    infoSections: [
        {
            title: '일정의 기준',
            isDefaultOpen: false,
            blocks: [
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '10/1은 저녁 도착·체크인, 10/7은 공항 이동만 배정합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '10/6은 예비일로 비워 둡니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '과학관은 플라네타리움만 관람합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '맥주 견학은 키린 코베공장과 아사히 스이타 뮤지엄입니다. 난바 키린시티는 일정에서 제외합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '10/5는 아사히 → 태양의 탑 → 국립민족학박물관입니다. 공원·일본정원 산책은 넣지 않습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '모든 시각은 일본 현지시각입니다. 한국과 시차는 없습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'heading',
                    emphasis: null,
                    text: '이동시간을 읽는 방법',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'paragraph',
                    emphasis: '‘일정 배정’은 출발지 문 앞부터 목적지까지의 승차·도보·환승·대기·여유를 더한 시간입니다.',
                    text: '표의 합계는 일정표에 반영했습니다. 역 출입·환승·보행시간은 개인차가 있어 계획값으로 계산했습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'paragraph',
                    emphasis: '모든 시간표 블록은 10분의 여유시간을 포함합니다.',
                    text: '일반 일정은 표시 구간의 마지막 10분을 여유로 두고, 항공편·키린 셔틀처럼 출발·도착 시각이 고정된 일정은 바로 앞이나 뒤의 대기 블록에서 10분을 확보합니다. 공식 운행 시각 자체는 변경하지 않습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'paragraph',
                    emphasis: '여행 날짜의 특정 열차 출발·도착 시각까지 확정한 시간표는 아닙니다.',
                    text: '조회된 철도 자료에는 다른 날짜의 표준 운행 예시가 포함되어 있고, 일부 경로 사이트는 상세 조회가 차단되었습니다. 따라서 승차시간은 현재 확인 가능한 표준값·범위, 도보와 대기는 추정값으로 구분했습니다. 키린 셔틀만 공식 게시 출발·도착 시각을 그대로 사용했습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'paragraph',
                    emphasis: null,
                    text: '투어·입장권은 아직 예약하지 않았으며, 아래 목표 회차의 잔여석도 확정하지 않았습니다. 키린 10/2 15:10과 아사히 10/5 오전 회차를 먼저 확보한 뒤 나머지 입장권을 구매하는 순서입니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
            ],
        },
        {
            title: '전체 일정',
            isDefaultOpen: false,
            blocks: [
                {
                    kind: 'day_table',
                    emphasis: null,
                    text: null,
                    linkLabel: null,
                    linkUrl: null,
                },
            ],
        },
        {
            title: '숙소와 교통 거점',
            isDefaultOpen: false,
            blocks: [
                {
                    kind: 'paragraph',
                    emphasis: '東横INN大阪心斎橋西 / Toyoko Inn Osaka Shinsaibashi Nishi',
                    text: '주소: 大阪府大阪市西区北堀江1-9-22',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '요츠바시역(四ツ橋) 4번 출구에서 도보 1분.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '니시오하시역(西大橋) 4번 출구에서 도보 2분.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '신사이바시역(心斎橋) 남17번 출구에서 도보 7분.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '체크인 15:00, 체크아웃 10:00. 조식 06:30~09:00.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '숙소에서 지하철을 탈 때는 역 입구까지의 시간 외에 플랫폼까지 내려가는 시간을 별도로 계산했습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'paragraph',
                    emphasis: null,
                    text: null,
                    linkLabel: '숙소 공식 안내·지도',
                    linkUrl: 'https://www.toyoko-inn.com/search/detail/00023/',
                },
            ],
        },
        {
            title: '아직 확정되지 않은 항목',
            isDefaultOpen: true,
            blocks: [
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '10/1 항공편명은 미제공입니다. 인천 제2터미널16:10 출발 → 칸사이 제1터미널18:05 도착은 확인되었습니다. 공항 이후 교통은 수속 종료시각에 맞춰 선택합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '10/7 귀국편은 칸사이 제1터미널11:10 출발 → 인천 제2터미널13:00 도착으로 확인되었습니다. 항공사·편명, 난바 출발 열차와 숙소 택시는 미확정입니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '키린 10/2 15:10, 아사히 10/5 10시대의 운영 회차·잔여석.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '10/3 카이유칸 개장시간·입장 슬롯과 플라네타리움 실제 프로그램.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '10/5 태양의 탑 회차.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'bullet',
                    emphasis: null,
                    text: '여행일의 개별 열차 출발시각과 환승 연결. 특히 10/2 히메지 → 아마가사키 → 산다역 13:10 전후 도착, 셔틀 승차장14:15 도착 조건으로 마지막 확인이 필요합니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
                {
                    kind: 'paragraph',
                    emphasis: null,
                    text: '위 항목을 제외한 방문 순서·체류시간·환승 경로는 이 문서를 기준으로 사용합니다. ‘정확한 열차 시각’이 미확정인 구간을 확정값으로 표시하지 않았으며, 예약 전 단계에서 사용할 수 있도록 도보·대기까지 포함한 이동 예산을 계산했습니다.',
                    linkLabel: null,
                    linkUrl: null,
                },
            ],
        },
    ],
} satisfies TripTemplateInput
