import type { PublicTrip } from '@/entities/trip/trip.type'

/** Stable public detail DTO. Database-only fields are intentionally not spread. */
export const toDeveloperTripDetail = (trip: PublicTrip) => ({
    id: trip.id,
    ownerId: trip.ownerId,
    title: trip.title,
    eyebrow: trip.eyebrow,
    destination: trip.destination,
    departureAirportCode: trip.departureAirportCode,
    startDate: trip.startDate,
    endDate: trip.endDate,
    customNights: trip.customNights,
    customDays: trip.customDays,
    periodNote: trip.periodNote,
    disclaimer: trip.disclaimer,
    verifiedOn: trip.verifiedOn,
    bufferPolicy: trip.bufferPolicy,
    bookingNote: trip.bookingNote,
    footerNote: trip.footerNote,
    sidebarNote: trip.sidebarNote,
    shareSlug: trip.shareSlug,
    isPublic: trip.isPublic,
    likeCount: trip.likeCount,
    revision: trip.revision,
    createdAt: trip.createdAt,
    updatedAt: trip.updatedAt,
    owner: trip.owner,
    destinations: trip.destinations.map((item) => ({ countryCode: item.countryCode, city: item.city })),
    flights: trip.flights.map((item) => ({
        direction: item.direction,
        label: item.label,
        departCode: item.departCode,
        departTime: item.departTime,
        departTerminal: item.departTerminal,
        arriveCode: item.arriveCode,
        arriveTime: item.arriveTime,
        arriveTerminal: item.arriveTerminal,
        flightNumber: item.flightNumber,
        note: item.note,
    })),
    lodgings: trip.lodgings.map((item) => ({
        name: item.name,
        nameLocal: item.nameLocal,
        address: item.address,
        accessNote: item.accessNote,
        checkIn: item.checkIn,
        checkOut: item.checkOut,
        url: item.url,
        note: item.note,
    })),
    sidebarLinks: trip.sidebarLinks.map((item) => ({ label: item.label, url: item.url, description: item.description })),
    scheduleKinds: trip.scheduleKinds.map((item) => ({
        key: item.key,
        label: item.label,
        legendLabel: item.legendLabel,
        colorToken: item.colorToken,
        bufferLabel: item.bufferLabel,
    })),
    days: (() => {
        const kindKeyById = new Map(trip.scheduleKinds.map((kind) => [kind.id, kind.key]))
        return trip.days.map((day) => ({
            date: day.date,
            shortLabel: day.shortLabel,
            title: day.title,
            subtitle: day.subtitle,
            overview: day.overview,
            planHeadline: day.planHeadline,
            planNote: day.planNote,
            closingHeadline: day.closingHeadline,
            closingNote: day.closingNote,
            morningSummary: day.morningSummary,
            afternoonSummary: day.afternoonSummary,
            eveningSummary: day.eveningSummary,
            facts: day.facts.map((item) => ({ label: item.label, value: item.value })),
            routes: day.routes.map((item) => ({
                origin: item.origin,
                destination: item.destination,
                minutes: item.minutes,
                pathText: item.pathText,
                formula: item.formula,
            })),
            scheduleItems: day.scheduleItems.map((item) => ({
                timeLabel: item.timeLabel,
                title: item.title,
                // `kindId` is an internal UUID. The public template contract uses the
                // stable schedule-kind key so a GET response can be sent back to PUT.
                kind: kindKeyById.get(item.kindId) ?? '',
                note: item.note,
                bufferNote: item.bufferNote,
                mapQuery: item.mapQuery,
            })),
            notes: day.notes.map((item) => ({ leading: item.leading, linkLabel: item.linkLabel, linkUrl: item.linkUrl, trailing: item.trailing })),
        }))
    })(),
    bookings: trip.bookings.map((item) => ({
        title: item.title,
        whenLabel: item.whenLabel,
        priority: item.priority,
        linkLabel: item.linkLabel,
        linkUrl: item.linkUrl,
        actionNote: item.actionNote,
        planStatus: item.planStatus,
        attachments: item.attachments.map((attachment) => ({ kind: attachment.kind, url: attachment.url, label: attachment.label })),
    })),
    infoSections: trip.infoSections.map((item) => ({
        title: item.title,
        isDefaultOpen: item.isDefaultOpen,
        blocks: item.blocks.map((block) => ({
            kind: block.kind,
            emphasis: block.emphasis,
            text: block.text,
            linkLabel: block.linkLabel,
            linkUrl: block.linkUrl,
        })),
    })),
})

export type DeveloperTripDetail = ReturnType<typeof toDeveloperTripDetail>
