import type { PublicTrip } from '@/entities/trip/trip.type'

/** Stable public detail DTO. Database-only fields are intentionally not spread. */
export const toDeveloperTripDetail = (trip: PublicTrip) => ({
    id: trip.id,
    ownerId: trip.ownerId,
    title: trip.title,
    eyebrow: trip.eyebrow,
    destination: trip.destination,
    departureAirportCode: trip.departureAirportCode,
    startDate: trip.startDate,
    endDate: trip.endDate,
    customNights: trip.customNights,
    customDays: trip.customDays,
    periodNote: trip.periodNote,
    disclaimer: trip.disclaimer,
    verifiedOn: trip.verifiedOn,
    bufferPolicy: trip.bufferPolicy,
    bookingNote: trip.bookingNote,
    footerNote: trip.footerNote,
    sidebarNote: trip.sidebarNote,
    shareSlug: trip.shareSlug,
    isPublic: trip.isPublic,
    likeCount: trip.likeCount,
    revision: trip.revision,
    createdAt: trip.createdAt,
    updatedAt: trip.updatedAt,
    owner: trip.owner,
    destinations: trip.destinations.map((item) => ({ id: item.id, countryCode: item.countryCode, city: item.city, orderIndex: item.sortOrder })),
    flights: trip.flights.map((item) => ({
        id: item.id,
        direction: item.direction,
        label: item.label,
        departCode: item.departCode,
        departTime: item.departTime,
        departTerminal: item.departTerminal,
        arriveCode: item.arriveCode,
        arriveTime: item.arriveTime,
        arriveTerminal: item.arriveTerminal,
        flightNumber: item.flightNumber,
        note: item.note,
    })),
    lodgings: trip.lodgings.map((item) => ({
        id: item.id,
        name: item.name,
        nameLocal: item.nameLocal,
        address: item.address,
        accessNote: item.accessNote,
        checkIn: item.checkIn,
        checkOut: item.checkOut,
        url: item.url,
        note: item.note,
    })),
    sidebarLinks: trip.sidebarLinks.map((item) => ({ id: item.id, label: item.label, url: item.url, description: item.description })),
    scheduleKinds: trip.scheduleKinds.map((item) => ({
        id: item.id,
        key: item.key,
        label: item.label,
        legendLabel: item.legendLabel,
        colorToken: item.colorToken,
        bufferLabel: item.bufferLabel,
    })),
    days: trip.days.map((day) => ({
        id: day.id,
        date: day.date,
        shortLabel: day.shortLabel,
        title: day.title,
        subtitle: day.subtitle,
        overview: day.overview,
        planHeadline: day.planHeadline,
        planNote: day.planNote,
        closingHeadline: day.closingHeadline,
        closingNote: day.closingNote,
        morningSummary: day.morningSummary,
        afternoonSummary: day.afternoonSummary,
        eveningSummary: day.eveningSummary,
        facts: day.facts.map((item) => ({ id: item.id, label: item.label, value: item.value })),
        routes: day.routes.map((item) => ({
            id: item.id,
            origin: item.origin,
            destination: item.destination,
            minutes: item.minutes,
            pathText: item.pathText,
            formula: item.formula,
        })),
        scheduleItems: day.scheduleItems.map((item) => ({
            id: item.id,
            timeLabel: item.timeLabel,
            title: item.title,
            kind: item.kindId,
            note: item.note,
            bufferNote: item.bufferNote,
            mapQuery: item.mapQuery,
        })),
        notes: day.notes.map((item) => ({
            id: item.id,
            leading: item.leading,
            linkLabel: item.linkLabel,
            linkUrl: item.linkUrl,
            trailing: item.trailing,
        })),
    })),
    bookings: trip.bookings.map((item) => ({
        id: item.id,
        title: item.title,
        whenLabel: item.whenLabel,
        priority: item.priority,
        linkLabel: item.linkLabel,
        linkUrl: item.linkUrl,
        actionNote: item.actionNote,
        planStatus: item.planStatus,
        attachments: item.attachments,
    })),
    infoSections: trip.infoSections.map((item) => ({
        id: item.id,
        title: item.title,
        isDefaultOpen: item.isDefaultOpen,
        blocks: item.blocks,
    })),
})

export type DeveloperTripDetail = ReturnType<typeof toDeveloperTripDetail>
