export const AUTH_ERROR_FALLBACK_MESSAGE = 'auth.errors.fallback'

export const AUTH_ERROR_MESSAGE = {
    USER_ALREADY_EXISTS: 'auth.errors.USER_ALREADY_EXISTS',
    USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL: 'auth.errors.USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL',
    USER_NOT_FOUND: 'auth.errors.USER_NOT_FOUND',
    INVALID_EMAIL: 'auth.errors.INVALID_EMAIL',
    INVALID_EMAIL_OR_PASSWORD: 'auth.errors.INVALID_EMAIL_OR_PASSWORD',
    INVALID_USERNAME_OR_PASSWORD: 'auth.errors.INVALID_USERNAME_OR_PASSWORD',
    INVALID_PASSWORD: 'auth.errors.INVALID_PASSWORD',
    INVALID_USER: 'auth.errors.INVALID_USER',
    PASSWORD_TOO_SHORT: 'auth.errors.PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG: 'auth.errors.PASSWORD_TOO_LONG',
    USERNAME_IS_ALREADY_TAKEN: 'auth.errors.USERNAME_IS_ALREADY_TAKEN',
    USERNAME_TOO_SHORT: 'auth.errors.USERNAME_TOO_SHORT',
    USERNAME_TOO_LONG: 'auth.errors.USERNAME_TOO_LONG',
    INVALID_USERNAME: 'auth.errors.INVALID_USERNAME',
    INVALID_DISPLAY_USERNAME: 'auth.errors.INVALID_DISPLAY_USERNAME',
    USERNAME_IS_IMMUTABLE: 'auth.errors.USERNAME_IS_IMMUTABLE',
    CREDENTIAL_ACCOUNT_NOT_FOUND: 'auth.errors.CREDENTIAL_ACCOUNT_NOT_FOUND',
    EMAIL_NOT_VERIFIED: 'auth.errors.EMAIL_NOT_VERIFIED',
    VERIFICATION_EMAIL_NOT_ENABLED: 'auth.errors.VERIFICATION_EMAIL_NOT_ENABLED',
    CONSENT_VERSION_MISMATCH: 'auth.errors.CONSENT_VERSION_MISMATCH',
    CONSENT_SAVE_FAILED: 'auth.errors.CONSENT_SAVE_FAILED',
    SESSION_EXPIRED: 'auth.errors.SESSION_EXPIRED',
    FAILED_TO_CREATE_USER: 'auth.errors.FAILED_TO_CREATE_USER',
    FAILED_TO_CREATE_SESSION: 'auth.errors.FAILED_TO_CREATE_SESSION',
    VALIDATION_ERROR: 'auth.errors.VALIDATION_ERROR',
    MISSING_FIELD: 'auth.errors.MISSING_FIELD',
    UNEXPECTED_ERROR: AUTH_ERROR_FALLBACK_MESSAGE,
} as const

export type AuthErrorCode = keyof typeof AUTH_ERROR_MESSAGE

const isAuthErrorCode = (code: string): code is AuthErrorCode => Object.hasOwn(AUTH_ERROR_MESSAGE, code)

export const getAuthErrorMessage = (code?: string | null) => (code && isAuthErrorCode(code) ? AUTH_ERROR_MESSAGE[code] : AUTH_ERROR_FALLBACK_MESSAGE)
