export const openApiDocument = {
    openapi: '3.1.0',
    info: {
        title: 'Trip Developer API',
        version: '1.1.0',
        description: 'Owner-scoped trip resources. Personal access tokens are shown once and must be sent as an Authorization Bearer header.',
    },
    servers: [{ url: '/api/v1', description: 'Trip API' }],
    security: [{ bearerAuth: [] }],
    paths: {
        '/token': {
            get: {
                'operationId': 'introspectToken',
                'summary': 'Inspect the current token',
                'x-required-scopes': ['token:inspect'],
                'security': [{ bearerAuth: [] }],
                'responses': {
                    '200': { $ref: '#/components/responses/TokenSuccess' },
                    '401': { $ref: '#/components/responses/Error' },
                    '403': { $ref: '#/components/responses/Error' },
                    '429': { $ref: '#/components/responses/RateLimited' },
                    '500': { $ref: '#/components/responses/Error' },
                },
            },
        },
        '/trips': {
            get: {
                'operationId': 'listTrips',
                'summary': 'List trips owned by the token subject',
                'x-required-scopes': ['trips:read'],
                'security': [{ bearerAuth: [] }],
                'parameters': [{ $ref: '#/components/parameters/Page' }, { $ref: '#/components/parameters/PageSize' }],
                'responses': {
                    '200': { $ref: '#/components/responses/TripListSuccess' },
                    '400': { $ref: '#/components/responses/Error' },
                    '401': { $ref: '#/components/responses/Error' },
                    '403': { $ref: '#/components/responses/Error' },
                    '429': { $ref: '#/components/responses/RateLimited' },
                    '500': { $ref: '#/components/responses/Error' },
                },
            },
            post: {
                'operationId': 'createTrip',
                'summary': 'Create a trip from basic details or a validated template',
                'x-required-scopes': ['trips:write'],
                'security': [{ bearerAuth: [] }],
                'parameters': [{ $ref: '#/components/parameters/IdempotencyKey' }],
                'requestBody': {
                    required: true,
                    content: {
                        'application/json': {
                            schema: { oneOf: [{ $ref: '#/components/schemas/BasicTripCreate' }, { $ref: '#/components/schemas/TripTemplate' }] },
                        },
                    },
                },
                'responses': {
                    '201': { $ref: '#/components/responses/CreatedTripSuccess' },
                    '400': { $ref: '#/components/responses/Error' },
                    '401': { $ref: '#/components/responses/Error' },
                    '403': { $ref: '#/components/responses/Error' },
                    '413': { $ref: '#/components/responses/Error' },
                    '429': { $ref: '#/components/responses/RateLimited' },
                    '500': { $ref: '#/components/responses/Error' },
                },
            },
        },
        '/trips/{tripId}': {
            parameters: [{ $ref: '#/components/parameters/TripId' }],
            get: {
                'operationId': 'getTrip',
                'summary': 'Get an owned trip',
                'x-required-scopes': ['trips:read'],
                'security': [{ bearerAuth: [] }],
                'responses': {
                    '200': {
                        description: 'Trip detail; the ETag header is the required write precondition.',
                        headers: { ETag: { schema: { type: 'string' } } },
                        content: { 'application/json': { schema: { $ref: '#/components/schemas/TripDetailSuccess' } } },
                    },
                    '401': { $ref: '#/components/responses/Error' },
                    '403': { $ref: '#/components/responses/Error' },
                    '404': { $ref: '#/components/responses/Error' },
                    '429': { $ref: '#/components/responses/RateLimited' },
                    '500': { $ref: '#/components/responses/Error' },
                },
            },
            put: {
                'operationId': 'replaceTrip',
                'summary': 'Replace an owned trip after an explicit confirmation and current ETag precondition',
                'x-required-scopes': ['trips:write'],
                'security': [{ bearerAuth: [] }],
                'parameters': [
                    { $ref: '#/components/parameters/IdempotencyKey' },
                    { $ref: '#/components/parameters/IfMatch' },
                    { $ref: '#/components/parameters/ReplaceConfirmation' },
                ],
                'requestBody': { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/TripTemplate' } } } },
                'responses': {
                    '200': {
                        description: 'Replacement result; ETag is the new current version.',
                        headers: { ETag: { schema: { type: 'string' } } },
                        content: { 'application/json': { schema: { $ref: '#/components/schemas/CreatedTripSuccess' } } },
                    },
                    '400': { $ref: '#/components/responses/Error' },
                    '401': { $ref: '#/components/responses/Error' },
                    '403': { $ref: '#/components/responses/Error' },
                    '404': { $ref: '#/components/responses/Error' },
                    '409': { $ref: '#/components/responses/Error' },
                    '412': { $ref: '#/components/responses/Error' },
                    '413': { $ref: '#/components/responses/Error' },
                    '428': { $ref: '#/components/responses/Error' },
                    '429': { $ref: '#/components/responses/RateLimited' },
                    '500': { $ref: '#/components/responses/Error' },
                },
            },
            delete: {
                'operationId': 'deleteTrip',
                'summary': 'Delete an owned trip after an explicit confirmation and current ETag precondition',
                'x-required-scopes': ['trips:write'],
                'security': [{ bearerAuth: [] }],
                'parameters': [
                    { $ref: '#/components/parameters/IdempotencyKey' },
                    { $ref: '#/components/parameters/IfMatch' },
                    { $ref: '#/components/parameters/DeleteConfirmation' },
                ],
                'responses': {
                    '200': { $ref: '#/components/responses/DeletedTripSuccess' },
                    '400': { $ref: '#/components/responses/Error' },
                    '401': { $ref: '#/components/responses/Error' },
                    '403': { $ref: '#/components/responses/Error' },
                    '404': { $ref: '#/components/responses/Error' },
                    '428': { $ref: '#/components/responses/Error' },
                    '412': { $ref: '#/components/responses/Error' },
                    '429': { $ref: '#/components/responses/RateLimited' },
                    '500': { $ref: '#/components/responses/Error' },
                },
            },
        },
    },
    components: {
        securitySchemes: {
            bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'trip_pat', description: 'Personal access token; never put it in a URL.' },
        },
        parameters: {
            TripId: { name: 'tripId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
            Page: { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 1000000, default: 1 } },
            PageSize: { name: 'page_size', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } },
            IdempotencyKey: { name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string', minLength: 1, maxLength: 255 } },
            IfMatch: {
                name: 'If-Match',
                in: 'header',
                required: true,
                description: 'The exact ETag returned by GET /trips/{tripId}; wildcard is not accepted.',
                schema: { type: 'string' },
            },
            ReplaceConfirmation: { name: 'X-Trip-Confirm', in: 'header', required: true, schema: { const: 'replace' } },
            DeleteConfirmation: { name: 'X-Trip-Confirm', in: 'header', required: true, schema: { const: 'delete' } },
        },
        schemas: {
            Success: { type: 'object', required: ['success', 'data'], properties: { success: { const: true }, data: {} } },
            TokenSuccess: {
                type: 'object',
                required: ['success', 'data'],
                properties: { success: { const: true }, data: { $ref: '#/components/schemas/TokenIntrospection' } },
            },
            CreatedTripSuccess: {
                type: 'object',
                required: ['success', 'data'],
                properties: { success: { const: true }, data: { $ref: '#/components/schemas/CreatedTrip' } },
            },
            TripListSuccess: {
                type: 'object',
                required: ['success', 'data'],
                properties: { success: { const: true }, data: { $ref: '#/components/schemas/TripListPage' } },
            },
            TripDetailSuccess: {
                type: 'object',
                required: ['success', 'data'],
                properties: { success: { const: true }, data: { $ref: '#/components/schemas/TripDetail' } },
            },
            DeletedTripSuccess: {
                type: 'object',
                required: ['success', 'data'],
                properties: { success: { const: true }, data: { $ref: '#/components/schemas/DeletedTrip' } },
            },
            TokenIntrospection: {
                type: 'object',
                required: ['token', 'capabilities', 'subject'],
                properties: {
                    token: {
                        type: 'object',
                        required: ['id', 'label', 'scopes', 'prefix', 'last4', 'createdAt', 'expiresAt', 'lastUsedAt'],
                        properties: {
                            id: { type: 'string', format: 'uuid' },
                            label: { type: 'string' },
                            scopes: { type: 'array', items: { enum: ['trips:read', 'trips:write', 'token:inspect'] } },
                            prefix: { type: 'string' },
                            last4: { type: 'string', minLength: 4, maxLength: 4 },
                            createdAt: { type: 'string', format: 'date-time' },
                            expiresAt: { type: ['string', 'null'], format: 'date-time' },
                            lastUsedAt: { type: ['string', 'null'], format: 'date-time' },
                        },
                        additionalProperties: false,
                    },
                    capabilities: { type: 'array', items: { enum: ['trips:read', 'trips:write', 'token:inspect'] } },
                    subject: { type: 'object', required: ['userId'], properties: { userId: { type: 'string', format: 'uuid' } } },
                },
                additionalProperties: false,
            },
            CreatedTrip: {
                type: 'object',
                required: ['id'],
                properties: { id: { type: 'string', format: 'uuid' } },
                additionalProperties: false,
            },
            DeletedTrip: {
                type: 'object',
                required: ['id', 'deleted'],
                properties: { id: { type: 'string', format: 'uuid' }, deleted: { const: true } },
                additionalProperties: false,
            },
            TripSummary: {
                type: 'object',
                required: [
                    'id',
                    'title',
                    'destination',
                    'startDate',
                    'endDate',
                    'role',
                    'dayCount',
                    'scheduleCount',
                    'bookingCount',
                    'updatedAt',
                    'isFavorite',
                ],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    title: { type: 'string' },
                    eyebrow: { type: ['string', 'null'] },
                    destination: { type: 'string' },
                    departureAirportCode: { type: ['string', 'null'] },
                    startDate: { type: 'string', format: 'date' },
                    endDate: { type: 'string', format: 'date' },
                    customNights: { type: ['integer', 'null'] },
                    customDays: { type: ['integer', 'null'] },
                    periodNote: { type: ['string', 'null'] },
                    role: { enum: ['owner', 'editor', 'viewer'] },
                    dayCount: { type: 'integer', minimum: 0 },
                    scheduleCount: { type: 'integer', minimum: 0 },
                    bookingCount: { type: 'integer', minimum: 0 },
                    updatedAt: { type: 'string', format: 'date-time' },
                    isFavorite: { type: 'boolean' },
                    destinations: { type: 'array', items: { $ref: '#/components/schemas/Destination' } },
                    flights: { type: 'array', items: { $ref: '#/components/schemas/TripSummaryFlight' } },
                },
                additionalProperties: false,
            },
            TripListPage: {
                type: 'object',
                required: ['items', 'page', 'pageSize', 'total', 'pageCount'],
                properties: {
                    items: { type: 'array', items: { $ref: '#/components/schemas/TripSummary' } },
                    page: { type: 'integer', minimum: 1 },
                    pageSize: { type: 'integer', minimum: 1, maximum: 100 },
                    total: { type: 'integer', minimum: 0 },
                    pageCount: { type: 'integer', minimum: 1 },
                },
                additionalProperties: false,
            },
            TripDetail: {
                type: 'object',
                required: [
                    'id',
                    'ownerId',
                    'title',
                    'destination',
                    'startDate',
                    'endDate',
                    'revision',
                    'createdAt',
                    'updatedAt',
                    'owner',
                    'destinations',
                    'flights',
                    'lodgings',
                    'days',
                ],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    ownerId: { type: 'string', format: 'uuid' },
                    title: { type: 'string' },
                    eyebrow: { type: ['string', 'null'] },
                    destination: { type: 'string' },
                    departureAirportCode: { type: ['string', 'null'] },
                    startDate: { type: 'string', format: 'date' },
                    endDate: { type: 'string', format: 'date' },
                    customNights: { type: ['integer', 'null'] },
                    customDays: { type: ['integer', 'null'] },
                    periodNote: { type: ['string', 'null'] },
                    disclaimer: { type: ['string', 'null'] },
                    verifiedOn: { type: ['string', 'null'], format: 'date' },
                    bufferPolicy: { type: ['string', 'null'] },
                    bookingNote: { type: ['string', 'null'] },
                    footerNote: { type: ['string', 'null'] },
                    sidebarNote: { type: ['string', 'null'] },
                    shareSlug: { type: ['string', 'null'] },
                    isPublic: { type: 'boolean' },
                    likeCount: { type: 'integer', minimum: 0 },
                    revision: { type: 'integer', minimum: 0 },
                    createdAt: { type: 'string', format: 'date-time' },
                    updatedAt: { type: 'string', format: 'date-time' },
                    owner: {
                        type: 'object',
                        required: ['id', 'name'],
                        properties: {
                            id: { type: 'string', format: 'uuid' },
                            name: { type: 'string' },
                            username: { type: ['string', 'null'] },
                            image: { type: ['string', 'null'] },
                        },
                    },
                    destinations: { type: 'array', items: { $ref: '#/components/schemas/Destination' } },
                    flights: { type: 'array', items: { $ref: '#/components/schemas/Flight' } },
                    lodgings: { type: 'array', items: { $ref: '#/components/schemas/Lodging' } },
                    sidebarLinks: { type: 'array', items: { $ref: '#/components/schemas/SidebarLink' } },
                    scheduleKinds: { type: 'array', items: { $ref: '#/components/schemas/ScheduleKind' } },
                    days: { type: 'array', items: { $ref: '#/components/schemas/Day' } },
                    bookings: { type: 'array', items: { $ref: '#/components/schemas/Booking' } },
                    infoSections: { type: 'array', items: { $ref: '#/components/schemas/InfoSection' } },
                },
                additionalProperties: false,
            },
            Error: {
                type: 'object',
                required: ['success', 'error'],
                properties: {
                    success: { const: false },
                    error: {
                        type: 'object',
                        required: ['code', 'message'],
                        properties: { code: { type: 'string' }, message: { type: 'string' }, details: { type: 'object' } },
                    },
                },
            },
            Destination: {
                type: 'object',
                required: ['countryCode'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    countryCode: { type: 'string', minLength: 2, maxLength: 2 },
                    city: { type: ['string', 'null'], maxLength: 120 },
                    orderIndex: { type: 'integer', minimum: 0 },
                },
                additionalProperties: false,
            },
            ScheduleKind: {
                type: 'object',
                required: ['key', 'label', 'legendLabel'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    key: { type: 'string', minLength: 1, maxLength: 40 },
                    label: { type: 'string', minLength: 1, maxLength: 80 },
                    legendLabel: { type: 'string', minLength: 1, maxLength: 80 },
                    colorToken: { type: 'string', maxLength: 40 },
                    bufferLabel: { type: ['string', 'null'], maxLength: 80 },
                },
                additionalProperties: false,
            },
            ScheduleItem: {
                type: 'object',
                required: ['timeLabel', 'title', 'kind'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    timeLabel: { type: 'string', maxLength: 40 },
                    title: { type: 'string', minLength: 1, maxLength: 200 },
                    kind: { type: 'string', minLength: 1, maxLength: 40 },
                    note: { type: ['string', 'null'], maxLength: 300 },
                    bufferNote: { type: ['string', 'null'], maxLength: 80 },
                    mapQuery: { type: ['string', 'null'], maxLength: 200 },
                },
                additionalProperties: false,
            },
            Day: {
                type: 'object',
                required: ['date', 'shortLabel', 'title'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    date: { type: 'string', format: 'date' },
                    shortLabel: { type: 'string', minLength: 1, maxLength: 40 },
                    title: { type: 'string', minLength: 1, maxLength: 120 },
                    subtitle: { type: ['string', 'null'], maxLength: 200 },
                    overview: { type: ['string', 'null'], maxLength: 2000 },
                    planHeadline: { type: ['string', 'null'], maxLength: 255 },
                    planNote: { type: ['string', 'null'], maxLength: 2000 },
                    closingHeadline: { type: ['string', 'null'], maxLength: 255 },
                    closingNote: { type: ['string', 'null'], maxLength: 2000 },
                    morningSummary: { type: ['string', 'null'], maxLength: 120 },
                    afternoonSummary: { type: ['string', 'null'], maxLength: 120 },
                    eveningSummary: { type: ['string', 'null'], maxLength: 120 },
                    facts: { type: 'array', maxItems: 50, items: { $ref: '#/components/schemas/DayFact' } },
                    routes: { type: 'array', maxItems: 100, items: { $ref: '#/components/schemas/Route' } },
                    scheduleItems: { type: 'array', maxItems: 200, items: { $ref: '#/components/schemas/ScheduleItem' } },
                    notes: { type: 'array', maxItems: 50, items: { $ref: '#/components/schemas/DayNote' } },
                },
                additionalProperties: false,
            },
            Flight: {
                type: 'object',
                required: ['direction', 'label', 'departCode', 'departTime', 'arriveCode', 'arriveTime'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    direction: { enum: ['outbound', 'inbound'] },
                    label: { type: 'string', minLength: 1, maxLength: 120 },
                    departCode: { type: 'string', minLength: 3, maxLength: 8 },
                    departTime: { type: 'string', minLength: 1, maxLength: 8 },
                    departTerminal: { type: ['string', 'null'], maxLength: 32 },
                    arriveCode: { type: 'string', minLength: 3, maxLength: 8 },
                    arriveTime: { type: 'string', minLength: 1, maxLength: 8 },
                    arriveTerminal: { type: ['string', 'null'], maxLength: 32 },
                    flightNumber: { type: ['string', 'null'], maxLength: 32 },
                    note: { type: ['string', 'null'], maxLength: 200 },
                },
                additionalProperties: false,
            },
            TripSummaryFlight: {
                type: 'object',
                required: ['direction', 'departCode', 'arriveCode'],
                properties: {
                    direction: { enum: ['outbound', 'inbound'] },
                    departCode: { type: 'string', minLength: 3, maxLength: 8 },
                    arriveCode: { type: 'string', minLength: 3, maxLength: 8 },
                },
                additionalProperties: false,
            },
            Lodging: {
                type: 'object',
                required: ['name'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    name: { type: 'string', minLength: 1, maxLength: 160 },
                    nameLocal: { type: ['string', 'null'], maxLength: 160 },
                    address: { type: ['string', 'null'], maxLength: 255 },
                    accessNote: { type: ['string', 'null'], maxLength: 255 },
                    checkIn: { type: ['string', 'null'], maxLength: 8 },
                    checkOut: { type: ['string', 'null'], maxLength: 8 },
                    url: { type: ['string', 'null'], format: 'uri', maxLength: 500 },
                    note: { type: ['string', 'null'], maxLength: 255 },
                },
                additionalProperties: false,
            },
            Booking: {
                type: 'object',
                required: ['title'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    title: { type: 'string', minLength: 1, maxLength: 120 },
                    whenLabel: { type: ['string', 'null'], maxLength: 120 },
                    priority: { enum: ['p1', 'p2', 'p3'] },
                    linkLabel: { type: ['string', 'null'], maxLength: 120 },
                    linkUrl: { type: ['string', 'null'], format: 'uri', maxLength: 500 },
                    actionNote: { type: ['string', 'null'], maxLength: 200 },
                    planStatus: { type: ['string', 'null'], maxLength: 80 },
                    attachments: { type: 'array', maxItems: 20, items: { type: 'object' } },
                },
                additionalProperties: false,
            },
            InfoSection: {
                type: 'object',
                required: ['title'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    title: { type: 'string', minLength: 1, maxLength: 120 },
                    isDefaultOpen: { type: 'boolean' },
                    blocks: { type: 'array', maxItems: 100, items: { type: 'object' } },
                },
                additionalProperties: false,
            },
            DayFact: {
                type: 'object',
                required: ['label', 'value'],
                properties: { label: { type: 'string', minLength: 1, maxLength: 80 }, value: { type: 'string', minLength: 1, maxLength: 255 } },
                additionalProperties: false,
            },
            Route: {
                type: 'object',
                required: ['origin', 'destination', 'minutes'],
                properties: {
                    origin: { type: 'string', minLength: 1, maxLength: 120 },
                    destination: { type: 'string', minLength: 1, maxLength: 120 },
                    minutes: { type: 'integer', minimum: 0, maximum: 10000 },
                    pathText: { type: ['string', 'null'], maxLength: 255 },
                    formula: { type: ['string', 'null'], maxLength: 255 },
                },
                additionalProperties: false,
            },
            DayNote: {
                type: 'object',
                properties: {
                    leading: { type: ['string', 'null'], maxLength: 2000 },
                    linkLabel: { type: ['string', 'null'], maxLength: 120 },
                    linkUrl: { type: ['string', 'null'], format: 'uri', maxLength: 500 },
                    trailing: { type: ['string', 'null'], maxLength: 2000 },
                },
                additionalProperties: false,
            },
            SidebarLink: {
                type: 'object',
                required: ['label', 'url'],
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    label: { type: 'string', minLength: 1, maxLength: 80 },
                    url: { type: 'string', format: 'uri', maxLength: 500 },
                    description: { type: ['string', 'null'], maxLength: 200 },
                },
                additionalProperties: false,
            },
            BasicTripCreate: {
                type: 'object',
                required: ['title', 'destination', 'startDate', 'endDate', 'destinations'],
                properties: {
                    title: { type: 'string', minLength: 1, maxLength: 120 },
                    destination: { type: 'string', minLength: 1, maxLength: 120 },
                    startDate: { type: 'string', format: 'date' },
                    endDate: { type: 'string', format: 'date' },
                    eyebrow: { type: ['string', 'null'], maxLength: 120 },
                    departureAirportCode: { type: ['string', 'null'], pattern: '^[A-Z]{3}$' },
                    customNights: { type: ['integer', 'null'], minimum: 0, maximum: 365 },
                    customDays: { type: ['integer', 'null'], minimum: 1, maximum: 366 },
                    periodNote: { type: ['string', 'null'], maxLength: 200 },
                    disclaimer: { type: ['string', 'null'], maxLength: 300 },
                    verifiedOn: { type: ['string', 'null'], format: 'date' },
                    bufferPolicy: { type: ['string', 'null'], maxLength: 2000 },
                    bookingNote: { type: ['string', 'null'], maxLength: 2000 },
                    footerNote: { type: ['string', 'null'], maxLength: 2000 },
                    destinations: { type: 'array', minItems: 1, maxItems: 20, items: { $ref: '#/components/schemas/Destination' } },
                },
                additionalProperties: false,
            },
            TripTemplate: {
                type: 'object',
                required: ['title', 'destination', 'startDate', 'endDate', 'destinations'],
                properties: {
                    title: { type: 'string', minLength: 1, maxLength: 120 },
                    eyebrow: { type: ['string', 'null'], maxLength: 120 },
                    destination: { type: 'string', minLength: 1, maxLength: 120 },
                    startDate: { type: 'string', format: 'date' },
                    endDate: { type: 'string', format: 'date' },
                    departureAirportCode: { type: ['string', 'null'], pattern: '^[A-Z]{3}$' },
                    customNights: { type: ['integer', 'null'], minimum: 0, maximum: 365 },
                    customDays: { type: ['integer', 'null'], minimum: 1, maximum: 366 },
                    periodNote: { type: ['string', 'null'], maxLength: 200 },
                    disclaimer: { type: ['string', 'null'], maxLength: 300 },
                    verifiedOn: { type: ['string', 'null'], format: 'date' },
                    bufferPolicy: { type: ['string', 'null'], maxLength: 2000 },
                    bookingNote: { type: ['string', 'null'], maxLength: 2000 },
                    footerNote: { type: ['string', 'null'], maxLength: 2000 },
                    sidebarNote: { type: ['string', 'null'], maxLength: 500 },
                    destinations: { type: 'array', minItems: 1, maxItems: 20, items: { $ref: '#/components/schemas/Destination' } },
                    flights: { type: 'array', maxItems: 20, items: { $ref: '#/components/schemas/Flight' } },
                    lodgings: { type: 'array', maxItems: 20, items: { $ref: '#/components/schemas/Lodging' } },
                    sidebarLinks: { type: 'array', maxItems: 30, items: { $ref: '#/components/schemas/SidebarLink' } },
                    scheduleKinds: { type: 'array', minItems: 1, maxItems: 30, items: { $ref: '#/components/schemas/ScheduleKind' } },
                    days: { type: 'array', maxItems: 100, items: { $ref: '#/components/schemas/Day' } },
                    bookings: { type: 'array', maxItems: 100, items: { $ref: '#/components/schemas/Booking' } },
                    infoSections: { type: 'array', maxItems: 50, items: { $ref: '#/components/schemas/InfoSection' } },
                },
                additionalProperties: false,
            },
        },
        responses: {
            Success: { description: 'Successful response', content: { 'application/json': { schema: { $ref: '#/components/schemas/Success' } } } },
            TokenSuccess: {
                description: 'Successful token introspection response',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/TokenSuccess' } } },
            },
            CreatedTripSuccess: {
                description: 'Trip created or replaced',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/CreatedTripSuccess' } } },
            },
            TripListSuccess: {
                description: 'Paginated owner trip list',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/TripListSuccess' } } },
            },
            TripDetailSuccess: {
                description: 'Owned trip detail',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/TripDetailSuccess' } } },
            },
            DeletedTripSuccess: {
                description: 'Trip deleted',
                content: { 'application/json': { schema: { $ref: '#/components/schemas/DeletedTripSuccess' } } },
            },
            Error: { description: 'Error response', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            RateLimited: {
                description: 'Rate limit exceeded',
                headers: {
                    'Retry-After': { schema: { type: 'integer' } },
                    'X-RateLimit-Limit': { schema: { type: 'integer' } },
                    'X-RateLimit-Remaining': { schema: { type: 'integer' } },
                    'X-RateLimit-Reset': { schema: { type: 'integer' } },
                },
                content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
            },
        },
    },
} as const
